package rekammedis

import "time"

// MonitoringEfekSampingObat tabel `monitoring_efek_samping_obat` (pelaporan efek samping obat, RMPelaporanEfekSampingObat).
type MonitoringEfekSampingObat struct {
	NoRawat           string     `gorm:"column:no_rawat;primaryKey;autoIncrement:false" json:"no_rawat"`
	NoLaporan         string     `gorm:"column:no_laporan" json:"no_laporan"`
	Tanggal           *time.Time `gorm:"column:tanggal" json:"tanggal"`
	Profesi           string     `gorm:"column:profesi" json:"profesi"`
	Nik               *string    `gorm:"column:nik" json:"nik"`
	KdBangsal         *string    `gorm:"column:kd_bangsal" json:"kd_bangsal"`
	BeratBadan        *string    `gorm:"column:berat_badan" json:"berat_badan"`
	PasienHamil       string     `gorm:"column:pasien_hamil" json:"pasien_hamil"`
	Kesudahan         string     `gorm:"column:kesudahan" json:"kesudahan"`
	PenyakitLain      string     `gorm:"column:penyakit_lain" json:"penyakit_lain"`
	PenyakitUtama     string     `gorm:"column:penyakit_utama" json:"penyakit_utama"`
	TanggalKejadian   *time.Time `gorm:"column:tanggal_kejadian" json:"tanggal_kejadian"`
	Manifestasi       string     `gorm:"column:manifestasi" json:"manifestasi"`
	MasalahKualitas   string     `gorm:"column:masalah_kualitas" json:"masalah_kualitas"`
	RiwayatEso        string     `gorm:"column:riwayat_eso" json:"riwayat_eso"`
	TanggalKesudahan  *time.Time `gorm:"column:tanggal_kesudahan" json:"tanggal_kesudahan"`
	HasilKesudahan    string     `gorm:"column:hasil_kesudahan" json:"hasil_kesudahan"`
	Obat1             string     `gorm:"column:obat1" json:"obat1"`
	Sedian1           string     `gorm:"column:sedian1" json:"sedian1"`
	ObatJkn1          string     `gorm:"column:obat_jkn1" json:"obat_jkn1"`
	Batch1            string     `gorm:"column:batch1" json:"batch1"`
	Cara1             string     `gorm:"column:cara1" json:"cara1"`
	Dosis1            string     `gorm:"column:dosis1" json:"dosis1"`
	TanggalMulai1     *time.Time `gorm:"column:tanggal_mulai1" json:"tanggal_mulai1"`
	TanggalAkhir1     *time.Time `gorm:"column:tanggal_akhir1" json:"tanggal_akhir1"`
	Indikasi1         string     `gorm:"column:indikasi1" json:"indikasi1"`
	Obat2             string     `gorm:"column:obat2" json:"obat2"`
	Sedian2           string     `gorm:"column:sedian2" json:"sedian2"`
	ObatJkn2          string     `gorm:"column:obat_jkn2" json:"obat_jkn2"`
	Batch2            string     `gorm:"column:batch2" json:"batch2"`
	Cara2             string     `gorm:"column:cara2" json:"cara2"`
	Dosis2            string     `gorm:"column:dosis2" json:"dosis2"`
	TanggalMulai2     *time.Time `gorm:"column:tanggal_mulai2" json:"tanggal_mulai2"`
	TanggalAkhir2     *time.Time `gorm:"column:tanggal_akhir2" json:"tanggal_akhir2"`
	Indikasi2         string     `gorm:"column:indikasi2" json:"indikasi2"`
	Obat3             string     `gorm:"column:obat3" json:"obat3"`
	Sedian3           string     `gorm:"column:sedian3" json:"sedian3"`
	ObatJkn3          string     `gorm:"column:obat_jkn3" json:"obat_jkn3"`
	Batch3            string     `gorm:"column:batch3" json:"batch3"`
	Cara3             string     `gorm:"column:cara3" json:"cara3"`
	Dosis3            string     `gorm:"column:dosis3" json:"dosis3"`
	TanggalMulai3     *time.Time `gorm:"column:tanggal_mulai3" json:"tanggal_mulai3"`
	TanggalAkhir3     *time.Time `gorm:"column:tanggal_akhir3" json:"tanggal_akhir3"`
	Indikasi3         string     `gorm:"column:indikasi3" json:"indikasi3"`
	Obat4             string     `gorm:"column:obat4" json:"obat4"`
	Sedian4           string     `gorm:"column:sedian4" json:"sedian4"`
	ObatJkn4          string     `gorm:"column:obat_jkn4" json:"obat_jkn4"`
	Batch4            string     `gorm:"column:batch4" json:"batch4"`
	Cara4             string     `gorm:"column:cara4" json:"cara4"`
	Dosis4            string     `gorm:"column:dosis4" json:"dosis4"`
	TanggalMulai4     *time.Time `gorm:"column:tanggal_mulai4" json:"tanggal_mulai4"`
	TanggalAkhir4     *time.Time `gorm:"column:tanggal_akhir4" json:"tanggal_akhir4"`
	Indikasi4         string     `gorm:"column:indikasi4" json:"indikasi4"`
	Obat5             string     `gorm:"column:obat5" json:"obat5"`
	Sedian5           string     `gorm:"column:sedian5" json:"sedian5"`
	ObatJkn5          string     `gorm:"column:obat_jkn5" json:"obat_jkn5"`
	Batch5            string     `gorm:"column:batch5" json:"batch5"`
	Cara5             string     `gorm:"column:cara5" json:"cara5"`
	Dosis5            string     `gorm:"column:dosis5" json:"dosis5"`
	TanggalMulai5     *time.Time `gorm:"column:tanggal_mulai5" json:"tanggal_mulai5"`
	TanggalAkhir5     *time.Time `gorm:"column:tanggal_akhir5" json:"tanggal_akhir5"`
	Indikasi5         string     `gorm:"column:indikasi5" json:"indikasi5"`
	Obat6             string     `gorm:"column:obat6" json:"obat6"`
	Sedian6           string     `gorm:"column:sedian6" json:"sedian6"`
	ObatJkn6          string     `gorm:"column:obat_jkn6" json:"obat_jkn6"`
	Batch6            string     `gorm:"column:batch6" json:"batch6"`
	Cara6             string     `gorm:"column:cara6" json:"cara6"`
	Dosis6            string     `gorm:"column:dosis6" json:"dosis6"`
	TanggalMulai6     *time.Time `gorm:"column:tanggal_mulai6" json:"tanggal_mulai6"`
	TanggalAkhir6     *time.Time `gorm:"column:tanggal_akhir6" json:"tanggal_akhir6"`
	Indikasi6         string     `gorm:"column:indikasi6" json:"indikasi6"`
	Obat7             string     `gorm:"column:obat7" json:"obat7"`
	Sedian7           string     `gorm:"column:sedian7" json:"sedian7"`
	ObatJkn7          string     `gorm:"column:obat_jkn7" json:"obat_jkn7"`
	Batch7            string     `gorm:"column:batch7" json:"batch7"`
	Cara7             string     `gorm:"column:cara7" json:"cara7"`
	Dosis7            string     `gorm:"column:dosis7" json:"dosis7"`
	TanggalMulai7     *time.Time `gorm:"column:tanggal_mulai7" json:"tanggal_mulai7"`
	TanggalAkhir7     *time.Time `gorm:"column:tanggal_akhir7" json:"tanggal_akhir7"`
	Indikasi7         string     `gorm:"column:indikasi7" json:"indikasi7"`
	Obat8             string     `gorm:"column:obat8" json:"obat8"`
	Sedian8           string     `gorm:"column:sedian8" json:"sedian8"`
	ObatJkn8          string     `gorm:"column:obat_jkn8" json:"obat_jkn8"`
	Batch8            string     `gorm:"column:batch8" json:"batch8"`
	Cara8             string     `gorm:"column:cara8" json:"cara8"`
	Dosis8            string     `gorm:"column:dosis8" json:"dosis8"`
	TanggalMulai8     *time.Time `gorm:"column:tanggal_mulai8" json:"tanggal_mulai8"`
	TanggalAkhir8     *time.Time `gorm:"column:tanggal_akhir8" json:"tanggal_akhir8"`
	Indikasi8         string     `gorm:"column:indikasi8" json:"indikasi8"`
	Obat9             string     `gorm:"column:obat9" json:"obat9"`
	Sedian9           string     `gorm:"column:sedian9" json:"sedian9"`
	ObatJkn9          string     `gorm:"column:obat_jkn9" json:"obat_jkn9"`
	Batch9            string     `gorm:"column:batch9" json:"batch9"`
	Cara9             string     `gorm:"column:cara9" json:"cara9"`
	Dosis9            string     `gorm:"column:dosis9" json:"dosis9"`
	TanggalMulai9     *time.Time `gorm:"column:tanggal_mulai9" json:"tanggal_mulai9"`
	TanggalAkhir9     *time.Time `gorm:"column:tanggal_akhir9" json:"tanggal_akhir9"`
	Indikasi9         string     `gorm:"column:indikasi9" json:"indikasi9"`
	Obat10            string     `gorm:"column:obat10" json:"obat10"`
	Sedian10          string     `gorm:"column:sedian10" json:"sedian10"`
	ObatJkn10         string     `gorm:"column:obat_jkn10" json:"obat_jkn10"`
	Batch10           string     `gorm:"column:batch10" json:"batch10"`
	Cara10            string     `gorm:"column:cara10" json:"cara10"`
	Dosis10           string     `gorm:"column:dosis10" json:"dosis10"`
	TanggalMulai10    *time.Time `gorm:"column:tanggal_mulai10" json:"tanggal_mulai10"`
	TanggalAkhir10    *time.Time `gorm:"column:tanggal_akhir10" json:"tanggal_akhir10"`
	Indikasi10        string     `gorm:"column:indikasi10" json:"indikasi10"`
	ReaksiSetelah     string     `gorm:"column:reaksi_setelah" json:"reaksi_setelah"`
	ReaksiSama        string     `gorm:"column:reaksi_sama" json:"reaksi_sama"`
	Naranjo1          string     `gorm:"column:naranjo1" json:"naranjo1"`
	NilaiNaranjo1     string     `gorm:"column:nilai_naranjo1" json:"nilai_naranjo1"`
	Naranjo2          string     `gorm:"column:naranjo2" json:"naranjo2"`
	NilaiNaranjo2     string     `gorm:"column:nilai_naranjo2" json:"nilai_naranjo2"`
	Naranjo3          string     `gorm:"column:naranjo3" json:"naranjo3"`
	NilaiNaranjo3     string     `gorm:"column:nilai_naranjo3" json:"nilai_naranjo3"`
	Naranjo4          string     `gorm:"column:naranjo4" json:"naranjo4"`
	NilaiNaranjo4     string     `gorm:"column:nilai_naranjo4" json:"nilai_naranjo4"`
	Naranjo5          string     `gorm:"column:naranjo5" json:"naranjo5"`
	NilaiNaranjo5     string     `gorm:"column:nilai_naranjo5" json:"nilai_naranjo5"`
	Naranjo6          string     `gorm:"column:naranjo6" json:"naranjo6"`
	NilaiNaranjo6     string     `gorm:"column:nilai_naranjo6" json:"nilai_naranjo6"`
	Naranjo7          string     `gorm:"column:naranjo7" json:"naranjo7"`
	NilaiNaranjo7     string     `gorm:"column:nilai_naranjo7" json:"nilai_naranjo7"`
	Naranjo8          string     `gorm:"column:naranjo8" json:"naranjo8"`
	NilaiNaranjo8     string     `gorm:"column:nilai_naranjo8" json:"nilai_naranjo8"`
	Naranjo9          string     `gorm:"column:naranjo9" json:"naranjo9"`
	NilaiNaranjo9     string     `gorm:"column:nilai_naranjo9" json:"nilai_naranjo9"`
	Naranjo10         string     `gorm:"column:naranjo10" json:"naranjo10"`
	NilaiNaranjo10    string     `gorm:"column:nilai_naranjo10" json:"nilai_naranjo10"`
	TotalNilaiNaranjo string     `gorm:"column:total_nilai_naranjo" json:"total_nilai_naranjo"`
	KategoriNaranjo   string     `gorm:"column:kategori_naranjo" json:"kategori_naranjo"`
}

func (MonitoringEfekSampingObat) TableName() string {
	return "monitoring_efek_samping_obat"
}
