package rekammedis

import "time"

// PenilaianAwalKeperawatanKebidanan tabel `penilaian_awal_keperawatan_kebidanan` (penilaian awal keperawatan kebidanan, RMPenilaianAwalKeperawatanKebidanan).
type PenilaianAwalKeperawatanKebidanan struct {
	NoRawat       string     `gorm:"column:no_rawat;primaryKey;autoIncrement:false" json:"no_rawat"`
	Tanggal       *time.Time `gorm:"column:tanggal" json:"tanggal"`
	Informasi     string     `gorm:"column:informasi" json:"informasi"`
	Td            string     `gorm:"column:td" json:"td"`
	Nadi          string     `gorm:"column:nadi" json:"nadi"`
	Rr            string     `gorm:"column:rr" json:"rr"`
	Suhu          string     `gorm:"column:suhu" json:"suhu"`
	Gcs           string     `gorm:"column:gcs" json:"gcs"`
	Bb            string     `gorm:"column:bb" json:"bb"`
	Tb            string     `gorm:"column:tb" json:"tb"`
	Lila          string     `gorm:"column:lila" json:"lila"`
	Bmi           string     `gorm:"column:bmi" json:"bmi"`
	Tfu           string     `gorm:"column:tfu" json:"tfu"`
	Tbj           string     `gorm:"column:tbj" json:"tbj"`
	Letak         string     `gorm:"column:letak" json:"letak"`
	Presentasi    string     `gorm:"column:presentasi" json:"presentasi"`
	Penurunan     string     `gorm:"column:penurunan" json:"penurunan"`
	His           string     `gorm:"column:his" json:"his"`
	Kekuatan      string     `gorm:"column:kekuatan" json:"kekuatan"`
	Lamanya       string     `gorm:"column:lamanya" json:"lamanya"`
	Bjj           string     `gorm:"column:bjj" json:"bjj"`
	KetBjj        string     `gorm:"column:ket_bjj" json:"ket_bjj"`
	Portio        string     `gorm:"column:portio" json:"portio"`
	Serviks       string     `gorm:"column:serviks" json:"serviks"`
	Ketuban       string     `gorm:"column:ketuban" json:"ketuban"`
	Hodge         string     `gorm:"column:hodge" json:"hodge"`
	Inspekulo     string     `gorm:"column:inspekulo" json:"inspekulo"`
	KetInspekulo  string     `gorm:"column:ket_inspekulo" json:"ket_inspekulo"`
	Ctg           string     `gorm:"column:ctg" json:"ctg"`
	KetCtg        string     `gorm:"column:ket_ctg" json:"ket_ctg"`
	Usg           string     `gorm:"column:usg" json:"usg"`
	KetUsg        string     `gorm:"column:ket_usg" json:"ket_usg"`
	Lab           string     `gorm:"column:lab" json:"lab"`
	KetLab        string     `gorm:"column:ket_lab" json:"ket_lab"`
	Lakmus        string     `gorm:"column:lakmus" json:"lakmus"`
	KetLakmus     string     `gorm:"column:ket_lakmus" json:"ket_lakmus"`
	Panggul       string     `gorm:"column:panggul" json:"panggul"`
	KeluhanUtama  string     `gorm:"column:keluhan_utama" json:"keluhan_utama"`
	Umur          string     `gorm:"column:umur" json:"umur"`
	Lama          string     `gorm:"column:lama" json:"lama"`
	Banyaknya     string     `gorm:"column:banyaknya" json:"banyaknya"`
	Haid          string     `gorm:"column:haid" json:"haid"`
	Siklus        string     `gorm:"column:siklus" json:"siklus"`
	KetSiklus     string     `gorm:"column:ket_siklus" json:"ket_siklus"`
	KetSiklus1    string     `gorm:"column:ket_siklus1" json:"ket_siklus1"`
	Status        string     `gorm:"column:status" json:"status"`
	Kali          string     `gorm:"column:kali" json:"kali"`
	Usia1         string     `gorm:"column:usia1" json:"usia1"`
	Ket1          string     `gorm:"column:ket1" json:"ket1"`
	Usia2         *string    `gorm:"column:usia2" json:"usia2"`
	Ket2          *string    `gorm:"column:ket2" json:"ket2"`
	Usia3         *string    `gorm:"column:usia3" json:"usia3"`
	Ket3          *string    `gorm:"column:ket3" json:"ket3"`
	Hpht          *time.Time `gorm:"column:hpht" json:"hpht"`
	UsiaKehamilan string     `gorm:"column:usia_kehamilan" json:"usia_kehamilan"`
	Tp            *time.Time `gorm:"column:tp" json:"tp"`
	Imunisasi     string     `gorm:"column:imunisasi" json:"imunisasi"`
	KetImunisasi  string     `gorm:"column:ket_imunisasi" json:"ket_imunisasi"`
	G             string     `gorm:"column:g" json:"g"`
	P             string     `gorm:"column:p" json:"p"`
	A             string     `gorm:"column:a" json:"a"`
	Hidup         string     `gorm:"column:hidup" json:"hidup"`
	Ginekologi    string     `gorm:"column:ginekologi" json:"ginekologi"`
	Kebiasaan     string     `gorm:"column:kebiasaan" json:"kebiasaan"`
	KetKebiasaan  string     `gorm:"column:ket_kebiasaan" json:"ket_kebiasaan"`
	Kebiasaan1    string     `gorm:"column:kebiasaan1" json:"kebiasaan1"`
	KetKebiasaan1 string     `gorm:"column:ket_kebiasaan1" json:"ket_kebiasaan1"`
	Kebiasaan2    string     `gorm:"column:kebiasaan2" json:"kebiasaan2"`
	KetKebiasaan2 string     `gorm:"column:ket_kebiasaan2" json:"ket_kebiasaan2"`
	Kebiasaan3    string     `gorm:"column:kebiasaan3" json:"kebiasaan3"`
	Kb            string     `gorm:"column:kb" json:"kb"`
	KetKb         string     `gorm:"column:ket_kb" json:"ket_kb"`
	Komplikasi    string     `gorm:"column:komplikasi" json:"komplikasi"`
	KetKomplikasi string     `gorm:"column:ket_komplikasi" json:"ket_komplikasi"`
	Berhenti      string     `gorm:"column:berhenti" json:"berhenti"`
	Alasan        string     `gorm:"column:alasan" json:"alasan"`
	AlatBantu     string     `gorm:"column:alat_bantu" json:"alat_bantu"`
	KetBantu      string     `gorm:"column:ket_bantu" json:"ket_bantu"`
	Prothesa      string     `gorm:"column:prothesa" json:"prothesa"`
	KetPro        string     `gorm:"column:ket_pro" json:"ket_pro"`
	Adl           string     `gorm:"column:adl" json:"adl"`
	StatusPsiko   string     `gorm:"column:status_psiko" json:"status_psiko"`
	KetPsiko      string     `gorm:"column:ket_psiko" json:"ket_psiko"`
	HubKeluarga   string     `gorm:"column:hub_keluarga" json:"hub_keluarga"`
	TinggalDengan string     `gorm:"column:tinggal_dengan" json:"tinggal_dengan"`
	KetTinggal    string     `gorm:"column:ket_tinggal" json:"ket_tinggal"`
	Ekonomi       string     `gorm:"column:ekonomi" json:"ekonomi"`
	Budaya        string     `gorm:"column:budaya" json:"budaya"`
	KetBudaya     string     `gorm:"column:ket_budaya" json:"ket_budaya"`
	Edukasi       string     `gorm:"column:edukasi" json:"edukasi"`
	KetEdukasi    string     `gorm:"column:ket_edukasi" json:"ket_edukasi"`
	BerjalanA     string     `gorm:"column:berjalan_a" json:"berjalan_a"`
	BerjalanB     string     `gorm:"column:berjalan_b" json:"berjalan_b"`
	BerjalanC     string     `gorm:"column:berjalan_c" json:"berjalan_c"`
	Hasil         string     `gorm:"column:hasil" json:"hasil"`
	Lapor         string     `gorm:"column:lapor" json:"lapor"`
	KetLapor      string     `gorm:"column:ket_lapor" json:"ket_lapor"`
	Sg1           string     `gorm:"column:sg1" json:"sg1"`
	Nilai1        string     `gorm:"column:nilai1" json:"nilai1"`
	Sg2           string     `gorm:"column:sg2" json:"sg2"`
	Nilai2        string     `gorm:"column:nilai2" json:"nilai2"`
	TotalHasil    string     `gorm:"column:total_hasil" json:"total_hasil"`
	Nyeri         string     `gorm:"column:nyeri" json:"nyeri"`
	Provokes      string     `gorm:"column:provokes" json:"provokes"`
	KetProvokes   string     `gorm:"column:ket_provokes" json:"ket_provokes"`
	Quality       string     `gorm:"column:quality" json:"quality"`
	KetQuality    string     `gorm:"column:ket_quality" json:"ket_quality"`
	Lokasi        string     `gorm:"column:lokasi" json:"lokasi"`
	Menyebar      string     `gorm:"column:menyebar" json:"menyebar"`
	SkalaNyeri    string     `gorm:"column:skala_nyeri" json:"skala_nyeri"`
	Durasi        string     `gorm:"column:durasi" json:"durasi"`
	NyeriHilang   string     `gorm:"column:nyeri_hilang" json:"nyeri_hilang"`
	KetNyeri      string     `gorm:"column:ket_nyeri" json:"ket_nyeri"`
	PadaDokter    string     `gorm:"column:pada_dokter" json:"pada_dokter"`
	KetDokter     string     `gorm:"column:ket_dokter" json:"ket_dokter"`
	Masalah       string     `gorm:"column:masalah" json:"masalah"`
	Tindakan      string     `gorm:"column:tindakan" json:"tindakan"`
	Nip           string     `gorm:"column:nip" json:"nip"`
}

func (PenilaianAwalKeperawatanKebidanan) TableName() string {
	return "penilaian_awal_keperawatan_kebidanan"
}
