package rekammedis

import "time"

// PenilaianAwalKeperawatanRanapNeonatus tabel `penilaian_awal_keperawatan_ranap_neonatus` (penilaian awal keperawatan ranap neonatus, RMPenilaianAwalKeperawatanRanapNeonatus).
type PenilaianAwalKeperawatanRanapNeonatus struct {
	NoRawat                                 string     `gorm:"column:no_rawat;primaryKey;autoIncrement:false" json:"no_rawat"`
	Tanggal                                 *time.Time `gorm:"column:tanggal" json:"tanggal"`
	AsalPasien                              *string    `gorm:"column:asal_pasien" json:"asal_pasien"`
	CaraMasuk                               *string    `gorm:"column:cara_masuk" json:"cara_masuk"`
	DiperolehDari                           *string    `gorm:"column:diperoleh_dari" json:"diperoleh_dari"`
	HubunganDenganPasien                    *string    `gorm:"column:hubungan_dengan_pasien" json:"hubungan_dengan_pasien"`
	KeluhanUtama                            *string    `gorm:"column:keluhan_utama" json:"keluhan_utama"`
	PrenatalG                               *string    `gorm:"column:prenatal_g" json:"prenatal_g"`
	PrenatalP                               *string    `gorm:"column:prenatal_p" json:"prenatal_p"`
	PrenatalA                               *string    `gorm:"column:prenatal_a" json:"prenatal_a"`
	PrenatalUk                              *string    `gorm:"column:prenatal_uk" json:"prenatal_uk"`
	PrenatalRiwayatPenyakitIbu              *string    `gorm:"column:prenatal_riwayat_penyakit_ibu" json:"prenatal_riwayat_penyakit_ibu"`
	PrenatalRiwayatPenyakitIbuKeterangan    *string    `gorm:"column:prenatal_riwayat_penyakit_ibu_keterangan" json:"prenatal_riwayat_penyakit_ibu_keterangan"`
	PrenatalRiwayatPengobatanIbuSelamaHamil *string    `gorm:"column:prenatal_riwayat_pengobatan_ibu_selama_hamil" json:"prenatal_riwayat_pengobatan_ibu_selama_hamil"`
	PrenatalPernahDirawat                   *string    `gorm:"column:prenatal_pernah_dirawat" json:"prenatal_pernah_dirawat"`
	PrenatalPernahDirawatKeterangan         *string    `gorm:"column:prenatal_pernah_dirawat_keterangan" json:"prenatal_pernah_dirawat_keterangan"`
	PrenatalStatusGiziIbu                   *string    `gorm:"column:prenatal_status_gizi_ibu" json:"prenatal_status_gizi_ibu"`
	IntranatalG                             *string    `gorm:"column:intranatal_g" json:"intranatal_g"`
	IntranatalP                             *string    `gorm:"column:intranatal_p" json:"intranatal_p"`
	IntranatalA                             *string    `gorm:"column:intranatal_a" json:"intranatal_a"`
	IntranatalKondisiLahir                  *string    `gorm:"column:intranatal_kondisi_lahir" json:"intranatal_kondisi_lahir"`
	IntranatalCaraPersalinan                *string    `gorm:"column:intranatal_cara_persalinan" json:"intranatal_cara_persalinan"`
	IntranatalCaraPersalinanKeterangan      *string    `gorm:"column:intranatal_cara_persalinan_keterangan" json:"intranatal_cara_persalinan_keterangan"`
	IntranatalApgar                         *string    `gorm:"column:intranatal_apgar" json:"intranatal_apgar"`
	IntranatalLetak                         *string    `gorm:"column:intranatal_letak" json:"intranatal_letak"`
	IntranatalTaliPusat                     *string    `gorm:"column:intranatal_tali_pusat" json:"intranatal_tali_pusat"`
	IntranatalKetuban                       string     `gorm:"column:intranatal_ketuban" json:"intranatal_ketuban"`
	IntranatalBb                            string     `gorm:"column:intranatal_bb" json:"intranatal_bb"`
	IntranatalPb                            string     `gorm:"column:intranatal_pb" json:"intranatal_pb"`
	IntranatalLk                            string     `gorm:"column:intranatal_lk" json:"intranatal_lk"`
	IntranatalLd                            string     `gorm:"column:intranatal_ld" json:"intranatal_ld"`
	IntranatalLp                            string     `gorm:"column:intranatal_lp" json:"intranatal_lp"`
	RisikoInfeksiMayor                      string     `gorm:"column:risiko_infeksi_mayor" json:"risiko_infeksi_mayor"`
	RisikoInfeksiMayorKeterangan            string     `gorm:"column:risiko_infeksi_mayor_keterangan" json:"risiko_infeksi_mayor_keterangan"`
	RisikoInfeksiMinor                      string     `gorm:"column:risiko_infeksi_minor" json:"risiko_infeksi_minor"`
	RisikoInfeksiMinorKeterangan            string     `gorm:"column:risiko_infeksi_minor_keterangan" json:"risiko_infeksi_minor_keterangan"`
	KebutuhanBiologisNutrisi                string     `gorm:"column:kebutuhan_biologis_nutrisi" json:"kebutuhan_biologis_nutrisi"`
	KebutuhanBiologisNutrisiKeterangan      string     `gorm:"column:kebutuhan_biologis_nutrisi_keterangan" json:"kebutuhan_biologis_nutrisi_keterangan"`
	KebutuhanBiologisNutrisiFrekuensi       string     `gorm:"column:kebutuhan_biologis_nutrisi_frekuensi" json:"kebutuhan_biologis_nutrisi_frekuensi"`
	KebutuhanBiologisNutrisiKali            string     `gorm:"column:kebutuhan_biologis_nutrisi_kali" json:"kebutuhan_biologis_nutrisi_kali"`
	KebutuhanBiologisBak                    string     `gorm:"column:kebutuhan_biologis_bak" json:"kebutuhan_biologis_bak"`
	KebutuhanBiologisBakKeterangan          string     `gorm:"column:kebutuhan_biologis_bak_keterangan" json:"kebutuhan_biologis_bak_keterangan"`
	KebutuhanBiologisBab                    string     `gorm:"column:kebutuhan_biologis_bab" json:"kebutuhan_biologis_bab"`
	KebutuhanBiologisBabKeterangan          string     `gorm:"column:kebutuhan_biologis_bab_keterangan" json:"kebutuhan_biologis_bab_keterangan"`
	AlergiObat                              string     `gorm:"column:alergi_obat" json:"alergi_obat"`
	AlergiObatKeterangan                    string     `gorm:"column:alergi_obat_keterangan" json:"alergi_obat_keterangan"`
	AlergiObatReaksi                        string     `gorm:"column:alergi_obat_reaksi" json:"alergi_obat_reaksi"`
	AlergiMakanan                           string     `gorm:"column:alergi_makanan" json:"alergi_makanan"`
	AlergiMakananKeterangan                 string     `gorm:"column:alergi_makanan_keterangan" json:"alergi_makanan_keterangan"`
	AlergiMakananReaksi                     string     `gorm:"column:alergi_makanan_reaksi" json:"alergi_makanan_reaksi"`
	AlergiLainnya                           string     `gorm:"column:alergi_lainnya" json:"alergi_lainnya"`
	AlergiLainnyaKeterangan                 string     `gorm:"column:alergi_lainnya_keterangan" json:"alergi_lainnya_keterangan"`
	AlergiLainnyaReaksi                     string     `gorm:"column:alergi_lainnya_reaksi" json:"alergi_lainnya_reaksi"`
	RiwayatPenyakitKeluarga                 string     `gorm:"column:riwayat_penyakit_keluarga" json:"riwayat_penyakit_keluarga"`
	RiwayatPenyakitKeluargaKeterangan       string     `gorm:"column:riwayat_penyakit_keluarga_keterangan" json:"riwayat_penyakit_keluarga_keterangan"`
	RiwayatImunisasi                        string     `gorm:"column:riwayat_imunisasi" json:"riwayat_imunisasi"`
	RiwayatImunisasiKeterangan              string     `gorm:"column:riwayat_imunisasi_keterangan" json:"riwayat_imunisasi_keterangan"`
	RiwayatTranfusiDarah                    string     `gorm:"column:riwayat_tranfusi_darah" json:"riwayat_tranfusi_darah"`
	RiwayatTranfusiDarahKeterangan          string     `gorm:"column:riwayat_tranfusi_darah_keterangan" json:"riwayat_tranfusi_darah_keterangan"`
	RiwayatTranfusiDarahReaksi              string     `gorm:"column:riwayat_tranfusi_darah_reaksi" json:"riwayat_tranfusi_darah_reaksi"`
	RiwayatTranfusiDarahReaksiKeterangan    string     `gorm:"column:riwayat_tranfusi_darah_reaksi_keterangan" json:"riwayat_tranfusi_darah_reaksi_keterangan"`
	KebiasanIbuObatDiminum                  string     `gorm:"column:kebiasan_ibu_obat_diminum" json:"kebiasan_ibu_obat_diminum"`
	KebiasanIbuObatDiminumKeterangan        string     `gorm:"column:kebiasan_ibu_obat_diminum_keterangan" json:"kebiasan_ibu_obat_diminum_keterangan"`
	KebiasanIbuNarkoba                      string     `gorm:"column:kebiasan_ibu_narkoba" json:"kebiasan_ibu_narkoba"`
	KebiasanIbuNarkobaKeterangan            string     `gorm:"column:kebiasan_ibu_narkoba_keterangan" json:"kebiasan_ibu_narkoba_keterangan"`
	KebiasanIbuMerokok                      string     `gorm:"column:kebiasan_ibu_merokok" json:"kebiasan_ibu_merokok"`
	KebiasanIbuMerokokKeterangan            string     `gorm:"column:kebiasan_ibu_merokok_keterangan" json:"kebiasan_ibu_merokok_keterangan"`
	KebiasanIbuAlkohol                      string     `gorm:"column:kebiasan_ibu_alkohol" json:"kebiasan_ibu_alkohol"`
	KebiasanIbuAlkoholKeterangan            string     `gorm:"column:kebiasan_ibu_alkohol_keterangan" json:"kebiasan_ibu_alkohol_keterangan"`
	Kesadaran                               string     `gorm:"column:kesadaran" json:"kesadaran"`
	KeadaanUmum                             string     `gorm:"column:keadaan_umum" json:"keadaan_umum"`
	Gcs                                     string     `gorm:"column:gcs" json:"gcs"`
	Td                                      string     `gorm:"column:td" json:"td"`
	Suhu                                    string     `gorm:"column:suhu" json:"suhu"`
	Hr                                      string     `gorm:"column:hr" json:"hr"`
	Rr                                      string     `gorm:"column:rr" json:"rr"`
	Spo2                                    string     `gorm:"column:spo2" json:"spo2"`
	DownScore                               string     `gorm:"column:down_score" json:"down_score"`
	Bb                                      string     `gorm:"column:bb" json:"bb"`
	Tb                                      string     `gorm:"column:tb" json:"tb"`
	Lk                                      string     `gorm:"column:lk" json:"lk"`
	Ld                                      string     `gorm:"column:ld" json:"ld"`
	Lp                                      string     `gorm:"column:lp" json:"lp"`
	GdBayi                                  string     `gorm:"column:gd_bayi" json:"gd_bayi"`
	GdIbu                                   string     `gorm:"column:gd_ibu" json:"gd_ibu"`
	GdAyah                                  string     `gorm:"column:gd_ayah" json:"gd_ayah"`
	SarafPusatGerakBayi                     string     `gorm:"column:saraf_pusat_gerak_bayi" json:"saraf_pusat_gerak_bayi"`
	SarafPusatKepala                        string     `gorm:"column:saraf_pusat_kepala" json:"saraf_pusat_kepala"`
	SarafPusatKepalaKeterangan              string     `gorm:"column:saraf_pusat_kepala_keterangan" json:"saraf_pusat_kepala_keterangan"`
	SarafPusatUbunubun                      string     `gorm:"column:saraf_pusat_ubunubun" json:"saraf_pusat_ubunubun"`
	SarafPusatUbunubunKeterangan            string     `gorm:"column:saraf_pusat_ubunubun_keterangan" json:"saraf_pusat_ubunubun_keterangan"`
	SarafPusatWajah                         string     `gorm:"column:saraf_pusat_wajah" json:"saraf_pusat_wajah"`
	SarafPusatWajahKeterangan               string     `gorm:"column:saraf_pusat_wajah_keterangan" json:"saraf_pusat_wajah_keterangan"`
	SarafPusatKejang                        string     `gorm:"column:saraf_pusat_kejang" json:"saraf_pusat_kejang"`
	SarafPusatKejangKeterangan              string     `gorm:"column:saraf_pusat_kejang_keterangan" json:"saraf_pusat_kejang_keterangan"`
	SarafPusatRefleks                       string     `gorm:"column:saraf_pusat_refleks" json:"saraf_pusat_refleks"`
	SarafPusatRefleksKeterangan             string     `gorm:"column:saraf_pusat_refleks_keterangan" json:"saraf_pusat_refleks_keterangan"`
	SarafPusatTangisbayi                    string     `gorm:"column:saraf_pusat_tangisbayi" json:"saraf_pusat_tangisbayi"`
	SarafPusatTangisbayiKeterangan          string     `gorm:"column:saraf_pusat_tangisbayi_keterangan" json:"saraf_pusat_tangisbayi_keterangan"`
	KardiovaskularDenyutnadi                string     `gorm:"column:kardiovaskular_denyutnadi" json:"kardiovaskular_denyutnadi"`
	KardiovaskularSirkulasi                 string     `gorm:"column:kardiovaskular_sirkulasi" json:"kardiovaskular_sirkulasi"`
	KardiovaskularSirkulasiKeterangan       string     `gorm:"column:kardiovaskular_sirkulasi_keterangan" json:"kardiovaskular_sirkulasi_keterangan"`
	KardiovaskularPulsasi                   string     `gorm:"column:kardiovaskular_pulsasi" json:"kardiovaskular_pulsasi"`
	KardiovaskularPulsasiKeterangan         string     `gorm:"column:kardiovaskular_pulsasi_keterangan" json:"kardiovaskular_pulsasi_keterangan"`
	RespirasiPolanafas                      string     `gorm:"column:respirasi_polanafas" json:"respirasi_polanafas"`
	RespirasiJenispernapasan                string     `gorm:"column:respirasi_jenispernapasan" json:"respirasi_jenispernapasan"`
	RespirasiJenispernapasanKeterangan      string     `gorm:"column:respirasi_jenispernapasan_keterangan" json:"respirasi_jenispernapasan_keterangan"`
	RespirasiRetraksi                       string     `gorm:"column:respirasi_retraksi" json:"respirasi_retraksi"`
	RespirasiAirentry                       string     `gorm:"column:respirasi_airentry" json:"respirasi_airentry"`
	RespirasiMerintih                       string     `gorm:"column:respirasi_merintih" json:"respirasi_merintih"`
	RespirasiSuaraNapas                     string     `gorm:"column:respirasi_suara_napas" json:"respirasi_suara_napas"`
	GastrointestinalMulut                   string     `gorm:"column:gastrointestinal_mulut" json:"gastrointestinal_mulut"`
	GastrointestinalMulutKeterangan         string     `gorm:"column:gastrointestinal_mulut_keterangan" json:"gastrointestinal_mulut_keterangan"`
	GastrointestinalLidah                   string     `gorm:"column:gastrointestinal_lidah" json:"gastrointestinal_lidah"`
	GastrointestinalLidahKeterangan         string     `gorm:"column:gastrointestinal_lidah_keterangan" json:"gastrointestinal_lidah_keterangan"`
	GastrointestinalTenggorakan             string     `gorm:"column:gastrointestinal_tenggorakan" json:"gastrointestinal_tenggorakan"`
	GastrointestinalTenggorakanKeterangan   string     `gorm:"column:gastrointestinal_tenggorakan_keterangan" json:"gastrointestinal_tenggorakan_keterangan"`
	GastrointestinalAbdomen                 string     `gorm:"column:gastrointestinal_abdomen" json:"gastrointestinal_abdomen"`
	GastrointestinalAbdomenKeterangan       string     `gorm:"column:gastrointestinal_abdomen_keterangan" json:"gastrointestinal_abdomen_keterangan"`
	GastrointestinalBab                     string     `gorm:"column:gastrointestinal_bab" json:"gastrointestinal_bab"`
	GastrointestinalBabKeterangan           string     `gorm:"column:gastrointestinal_bab_keterangan" json:"gastrointestinal_bab_keterangan"`
	GastrointestinalWarnabab                string     `gorm:"column:gastrointestinal_warnabab" json:"gastrointestinal_warnabab"`
	GastrointestinalWarnababKeterangan      string     `gorm:"column:gastrointestinal_warnabab_keterangan" json:"gastrointestinal_warnabab_keterangan"`
	GastrointestinalBak                     string     `gorm:"column:gastrointestinal_bak" json:"gastrointestinal_bak"`
	GastrointestinalBakKeterangan           string     `gorm:"column:gastrointestinal_bak_keterangan" json:"gastrointestinal_bak_keterangan"`
	GastrointestinalBakwarna                string     `gorm:"column:gastrointestinal_bakwarna" json:"gastrointestinal_bakwarna"`
	GastrointestinalBakwarnaKeterangan      string     `gorm:"column:gastrointestinal_bakwarna_keterangan" json:"gastrointestinal_bakwarna_keterangan"`
	NeurologiPosisiMata                     string     `gorm:"column:neurologi_posisi_mata" json:"neurologi_posisi_mata"`
	NeurologiKelopakMata                    string     `gorm:"column:neurologi_kelopak_mata" json:"neurologi_kelopak_mata"`
	NeurologiKelopakMataKeterangan          string     `gorm:"column:neurologi_kelopak_mata_keterangan" json:"neurologi_kelopak_mata_keterangan"`
	NeurologiBesarPupil                     string     `gorm:"column:neurologi_besar_pupil" json:"neurologi_besar_pupil"`
	NeurologiKonjugtiva                     string     `gorm:"column:neurologi_konjugtiva" json:"neurologi_konjugtiva"`
	NeurologiKonjugtivaKeterangan           string     `gorm:"column:neurologi_konjugtiva_keterangan" json:"neurologi_konjugtiva_keterangan"`
	NeurologiSklera                         string     `gorm:"column:neurologi_sklera" json:"neurologi_sklera"`
	NeurologiSkleraKeterangan               string     `gorm:"column:neurologi_sklera_keterangan" json:"neurologi_sklera_keterangan"`
	NeurologiPendengaran                    string     `gorm:"column:neurologi_pendengaran" json:"neurologi_pendengaran"`
	NeurologiPendengaranKeterangan          string     `gorm:"column:neurologi_pendengaran_keterangan" json:"neurologi_pendengaran_keterangan"`
	NeurologiPenciuman                      string     `gorm:"column:neurologi_penciuman" json:"neurologi_penciuman"`
	NeurologiPenciumanKeterangan            string     `gorm:"column:neurologi_penciuman_keterangan" json:"neurologi_penciuman_keterangan"`
	IntegumentWarnaKulit                    string     `gorm:"column:integument_warna_kulit" json:"integument_warna_kulit"`
	IntegumentWarnaKulitKeterangan          string     `gorm:"column:integument_warna_kulit_keterangan" json:"integument_warna_kulit_keterangan"`
	IntegumentVernicKaseosa                 string     `gorm:"column:integument_vernic_kaseosa" json:"integument_vernic_kaseosa"`
	IntegumentVernicKaseosaKeterangan       string     `gorm:"column:integument_vernic_kaseosa_keterangan" json:"integument_vernic_kaseosa_keterangan"`
	IntegumentTurgor                        string     `gorm:"column:integument_turgor" json:"integument_turgor"`
	IntegumentLanugo                        string     `gorm:"column:integument_lanugo" json:"integument_lanugo"`
	IntegumentKulit                         string     `gorm:"column:integument_kulit" json:"integument_kulit"`
	IntegumentRisikoDekubitas               string     `gorm:"column:integument_risiko_dekubitas" json:"integument_risiko_dekubitas"`
	Reproduksi                              string     `gorm:"column:reproduksi" json:"reproduksi"`
	ReproduksiKeterangan                    string     `gorm:"column:reproduksi_keterangan" json:"reproduksi_keterangan"`
	MuskuloskeletalRekoilTelinga            string     `gorm:"column:muskuloskeletal_rekoil_telinga" json:"muskuloskeletal_rekoil_telinga"`
	MuskuloskeletalRekoilTelingaKeterangan  string     `gorm:"column:muskuloskeletal_rekoil_telinga_keterangan" json:"muskuloskeletal_rekoil_telinga_keterangan"`
	MuskuloskeletalLengan                   string     `gorm:"column:muskuloskeletal_lengan" json:"muskuloskeletal_lengan"`
	MuskuloskeletalLenganKeterangan         string     `gorm:"column:muskuloskeletal_lengan_keterangan" json:"muskuloskeletal_lengan_keterangan"`
	MuskuloskeletalTungkai                  string     `gorm:"column:muskuloskeletal_tungkai" json:"muskuloskeletal_tungkai"`
	MuskuloskeletalTungkaiKeterangan        string     `gorm:"column:muskuloskeletal_tungkai_keterangan" json:"muskuloskeletal_tungkai_keterangan"`
	MuskuloskeletalTelapakKaki              string     `gorm:"column:muskuloskeletal_telapak_kaki" json:"muskuloskeletal_telapak_kaki"`
	KondisiPsikologis                       string     `gorm:"column:kondisi_psikologis" json:"kondisi_psikologis"`
	GangguanJiwa                            string     `gorm:"column:gangguan_jiwa" json:"gangguan_jiwa"`
	MenerimaKondisiBayi                     string     `gorm:"column:menerima_kondisi_bayi" json:"menerima_kondisi_bayi"`
	StatusMenikah                           string     `gorm:"column:status_menikah" json:"status_menikah"`
	MasalahPernikahan                       string     `gorm:"column:masalah_pernikahan" json:"masalah_pernikahan"`
	MasalahPernikahanKeterangan             string     `gorm:"column:masalah_pernikahan_keterangan" json:"masalah_pernikahan_keterangan"`
	Pekerjaan                               string     `gorm:"column:pekerjaan" json:"pekerjaan"`
	Agama                                   string     `gorm:"column:agama" json:"agama"`
	NilaiKepercayaan                        string     `gorm:"column:nilai_kepercayaan" json:"nilai_kepercayaan"`
	NilaiKepercayaanKeterangan              string     `gorm:"column:nilai_kepercayaan_keterangan" json:"nilai_kepercayaan_keterangan"`
	Suku                                    string     `gorm:"column:suku" json:"suku"`
	Pendidikan                              string     `gorm:"column:pendidikan" json:"pendidikan"`
	Pembayaran                              string     `gorm:"column:pembayaran" json:"pembayaran"`
	TinggalBersama                          string     `gorm:"column:tinggal_bersama" json:"tinggal_bersama"`
	TinggalBersamaKeterangan                string     `gorm:"column:tinggal_bersama_keterangan" json:"tinggal_bersama_keterangan"`
	HubunganKeluarga                        string     `gorm:"column:hubungan_keluarga" json:"hubungan_keluarga"`
	ResponEmosi                             string     `gorm:"column:respon_emosi" json:"respon_emosi"`
	BahasaSehariHari                        string     `gorm:"column:bahasa_sehari_hari" json:"bahasa_sehari_hari"`
	KemampuanBacatulis                      string     `gorm:"column:kemampuan_bacatulis" json:"kemampuan_bacatulis"`
	ButuhPenterjemah                        string     `gorm:"column:butuh_penterjemah" json:"butuh_penterjemah"`
	ButuhPenterjemahKeterangan              string     `gorm:"column:butuh_penterjemah_keterangan" json:"butuh_penterjemah_keterangan"`
	TerdapatHambatanBelajar                 string     `gorm:"column:terdapat_hambatan_belajar" json:"terdapat_hambatan_belajar"`
	HambatanBelajar                         string     `gorm:"column:hambatan_belajar" json:"hambatan_belajar"`
	HambatanBelajarKeterangan               string     `gorm:"column:hambatan_belajar_keterangan" json:"hambatan_belajar_keterangan"`
	HambatanCaraBicara                      string     `gorm:"column:hambatan_cara_bicara" json:"hambatan_cara_bicara"`
	HambatanBahasaIsyarat                   string     `gorm:"column:hambatan_bahasa_isyarat" json:"hambatan_bahasa_isyarat"`
	CaraBelajarDisukai                      string     `gorm:"column:cara_belajar_disukai" json:"cara_belajar_disukai"`
	KesediaanMenerimaInformasi              string     `gorm:"column:kesediaan_menerima_informasi" json:"kesediaan_menerima_informasi"`
	KesediaanMenerimaInformasiKeterangan    string     `gorm:"column:kesediaan_menerima_informasi_keterangan" json:"kesediaan_menerima_informasi_keterangan"`
	PemahamanNutrisi                        string     `gorm:"column:pemahaman_nutrisi" json:"pemahaman_nutrisi"`
	PemahamanPenyakit                       string     `gorm:"column:pemahaman_penyakit" json:"pemahaman_penyakit"`
	PemahamanPengobatan                     string     `gorm:"column:pemahaman_pengobatan" json:"pemahaman_pengobatan"`
	PemahamanPerawatan                      string     `gorm:"column:pemahaman_perawatan" json:"pemahaman_perawatan"`
	MasalahGizi1                            string     `gorm:"column:masalah_gizi1" json:"masalah_gizi1"`
	NilaiGizi1                              string     `gorm:"column:nilai_gizi1" json:"nilai_gizi1"`
	MasalahGizi2                            string     `gorm:"column:masalah_gizi2" json:"masalah_gizi2"`
	NilaiGizi2                              string     `gorm:"column:nilai_gizi2" json:"nilai_gizi2"`
	MasalahGizi3                            string     `gorm:"column:masalah_gizi3" json:"masalah_gizi3"`
	NilaiGizi3                              string     `gorm:"column:nilai_gizi3" json:"nilai_gizi3"`
	Totalgizi                               int        `gorm:"column:totalgizi" json:"totalgizi"`
	KeteranganGizi                          string     `gorm:"column:keterangan_gizi" json:"keterangan_gizi"`
	PenilaianHumptydumptySkala1             string     `gorm:"column:penilaian_humptydumpty_skala1" json:"penilaian_humptydumpty_skala1"`
	PenilaianHumptydumptyNilai1             int        `gorm:"column:penilaian_humptydumpty_nilai1" json:"penilaian_humptydumpty_nilai1"`
	PenilaianHumptydumptySkala2             string     `gorm:"column:penilaian_humptydumpty_skala2" json:"penilaian_humptydumpty_skala2"`
	PenilaianHumptydumptyNilai2             int        `gorm:"column:penilaian_humptydumpty_nilai2" json:"penilaian_humptydumpty_nilai2"`
	PenilaianHumptydumptySkala3             string     `gorm:"column:penilaian_humptydumpty_skala3" json:"penilaian_humptydumpty_skala3"`
	PenilaianHumptydumptyNilai3             int        `gorm:"column:penilaian_humptydumpty_nilai3" json:"penilaian_humptydumpty_nilai3"`
	PenilaianHumptydumptySkala4             string     `gorm:"column:penilaian_humptydumpty_skala4" json:"penilaian_humptydumpty_skala4"`
	PenilaianHumptydumptyNilai4             int        `gorm:"column:penilaian_humptydumpty_nilai4" json:"penilaian_humptydumpty_nilai4"`
	PenilaianHumptydumptySkala5             string     `gorm:"column:penilaian_humptydumpty_skala5" json:"penilaian_humptydumpty_skala5"`
	PenilaianHumptydumptyNilai5             int        `gorm:"column:penilaian_humptydumpty_nilai5" json:"penilaian_humptydumpty_nilai5"`
	PenilaianHumptydumptySkala6             string     `gorm:"column:penilaian_humptydumpty_skala6" json:"penilaian_humptydumpty_skala6"`
	PenilaianHumptydumptyNilai6             int        `gorm:"column:penilaian_humptydumpty_nilai6" json:"penilaian_humptydumpty_nilai6"`
	PenilaianHumptydumptySkala7             string     `gorm:"column:penilaian_humptydumpty_skala7" json:"penilaian_humptydumpty_skala7"`
	PenilaianHumptydumptyNilai7             int        `gorm:"column:penilaian_humptydumpty_nilai7" json:"penilaian_humptydumpty_nilai7"`
	PenilaianHumptydumptyTotalnilai         int        `gorm:"column:penilaian_humptydumpty_totalnilai" json:"penilaian_humptydumpty_totalnilai"`
	PenilaianHumptydumptyHasil              string     `gorm:"column:penilaian_humptydumpty_hasil" json:"penilaian_humptydumpty_hasil"`
	SkalaNips1                              string     `gorm:"column:skala_nips1" json:"skala_nips1"`
	SkalaNips1Nilai                         string     `gorm:"column:skala_nips1_nilai" json:"skala_nips1_nilai"`
	SkalaNips2                              string     `gorm:"column:skala_nips2" json:"skala_nips2"`
	SkalaNips2Nilai                         string     `gorm:"column:skala_nips2_nilai" json:"skala_nips2_nilai"`
	SkalaNips3                              string     `gorm:"column:skala_nips3" json:"skala_nips3"`
	SkalaNips3Nilai                         string     `gorm:"column:skala_nips3_nilai" json:"skala_nips3_nilai"`
	SkalaNips4                              string     `gorm:"column:skala_nips4" json:"skala_nips4"`
	SkalaNips4Nilai                         string     `gorm:"column:skala_nips4_nilai" json:"skala_nips4_nilai"`
	SkalaNips5                              string     `gorm:"column:skala_nips5" json:"skala_nips5"`
	SkalaNips5Nilai                         string     `gorm:"column:skala_nips5_nilai" json:"skala_nips5_nilai"`
	SkalaNipsTotal                          int        `gorm:"column:skala_nips_total" json:"skala_nips_total"`
	SkalaNipsKeterangan                     string     `gorm:"column:skala_nips_keterangan" json:"skala_nips_keterangan"`
	InformasiPerencanaanPulang              string     `gorm:"column:informasi_perencanaan_pulang" json:"informasi_perencanaan_pulang"`
	LamaRatarata                            string     `gorm:"column:lama_ratarata" json:"lama_ratarata"`
	PerencanaanPulang                       *time.Time `gorm:"column:perencanaan_pulang" json:"perencanaan_pulang"`
	KondisiKlinisPulang                     string     `gorm:"column:kondisi_klinis_pulang" json:"kondisi_klinis_pulang"`
	PerawatanLanjutanDirumah                string     `gorm:"column:perawatan_lanjutan_dirumah" json:"perawatan_lanjutan_dirumah"`
	CaraTransportasiPulang                  string     `gorm:"column:cara_transportasi_pulang" json:"cara_transportasi_pulang"`
	TransportasiDigunakan                   string     `gorm:"column:transportasi_digunakan" json:"transportasi_digunakan"`
	Rencana                                 *string    `gorm:"column:rencana" json:"rencana"`
	Nip1                                    string     `gorm:"column:nip1" json:"nip1"`
	Nip2                                    string     `gorm:"column:nip2" json:"nip2"`
	KdDokter                                string     `gorm:"column:kd_dokter" json:"kd_dokter"`
}

func (PenilaianAwalKeperawatanRanapNeonatus) TableName() string {
	return "penilaian_awal_keperawatan_ranap_neonatus"
}
