package rekammedis

import "time"

// PenilaianAwalKeperawatanRanap tabel `penilaian_awal_keperawatan_ranap` (penilaian awal keperawatan ranap, RMPenilaianAwalKeperawatanRanap).
type PenilaianAwalKeperawatanRanap struct {
	NoRawat                                          string     `gorm:"column:no_rawat;primaryKey;autoIncrement:false" json:"no_rawat"`
	Tanggal                                          *time.Time `gorm:"column:tanggal" json:"tanggal"`
	Informasi                                        string     `gorm:"column:informasi" json:"informasi"`
	KetInformasi                                     string     `gorm:"column:ket_informasi" json:"ket_informasi"`
	TibaDiruangRawat                                 string     `gorm:"column:tiba_diruang_rawat" json:"tiba_diruang_rawat"`
	KasusTrauma                                      *string    `gorm:"column:kasus_trauma" json:"kasus_trauma"`
	CaraMasuk                                        string     `gorm:"column:cara_masuk" json:"cara_masuk"`
	Rps                                              string     `gorm:"column:rps" json:"rps"`
	Rpd                                              string     `gorm:"column:rpd" json:"rpd"`
	Rpk                                              string     `gorm:"column:rpk" json:"rpk"`
	Rpo                                              string     `gorm:"column:rpo" json:"rpo"`
	RiwayatPembedahan                                string     `gorm:"column:riwayat_pembedahan" json:"riwayat_pembedahan"`
	RiwayatDirawatDirs                               string     `gorm:"column:riwayat_dirawat_dirs" json:"riwayat_dirawat_dirs"`
	AlatBantuDipakai                                 string     `gorm:"column:alat_bantu_dipakai" json:"alat_bantu_dipakai"`
	RiwayatKehamilan                                 string     `gorm:"column:riwayat_kehamilan" json:"riwayat_kehamilan"`
	RiwayatKehamilanPerkiraan                        string     `gorm:"column:riwayat_kehamilan_perkiraan" json:"riwayat_kehamilan_perkiraan"`
	RiwayatTranfusi                                  string     `gorm:"column:riwayat_tranfusi" json:"riwayat_tranfusi"`
	RiwayatAlergi                                    string     `gorm:"column:riwayat_alergi" json:"riwayat_alergi"`
	RiwayatMerokok                                   string     `gorm:"column:riwayat_merokok" json:"riwayat_merokok"`
	RiwayatMerokokJumlah                             string     `gorm:"column:riwayat_merokok_jumlah" json:"riwayat_merokok_jumlah"`
	RiwayatAlkohol                                   string     `gorm:"column:riwayat_alkohol" json:"riwayat_alkohol"`
	RiwayatAlkoholJumlah                             string     `gorm:"column:riwayat_alkohol_jumlah" json:"riwayat_alkohol_jumlah"`
	RiwayatNarkoba                                   string     `gorm:"column:riwayat_narkoba" json:"riwayat_narkoba"`
	RiwayatOlahraga                                  string     `gorm:"column:riwayat_olahraga" json:"riwayat_olahraga"`
	PemeriksaanMental                                string     `gorm:"column:pemeriksaan_mental" json:"pemeriksaan_mental"`
	PemeriksaanKeadaanUmum                           string     `gorm:"column:pemeriksaan_keadaan_umum" json:"pemeriksaan_keadaan_umum"`
	PemeriksaanGcs                                   string     `gorm:"column:pemeriksaan_gcs" json:"pemeriksaan_gcs"`
	PemeriksaanTd                                    string     `gorm:"column:pemeriksaan_td" json:"pemeriksaan_td"`
	PemeriksaanNadi                                  string     `gorm:"column:pemeriksaan_nadi" json:"pemeriksaan_nadi"`
	PemeriksaanRr                                    string     `gorm:"column:pemeriksaan_rr" json:"pemeriksaan_rr"`
	PemeriksaanSuhu                                  string     `gorm:"column:pemeriksaan_suhu" json:"pemeriksaan_suhu"`
	PemeriksaanSpo2                                  string     `gorm:"column:pemeriksaan_spo2" json:"pemeriksaan_spo2"`
	PemeriksaanBb                                    string     `gorm:"column:pemeriksaan_bb" json:"pemeriksaan_bb"`
	PemeriksaanTb                                    string     `gorm:"column:pemeriksaan_tb" json:"pemeriksaan_tb"`
	PemeriksaanSusunanKepala                         string     `gorm:"column:pemeriksaan_susunan_kepala" json:"pemeriksaan_susunan_kepala"`
	PemeriksaanSusunanKepalaKeterangan               string     `gorm:"column:pemeriksaan_susunan_kepala_keterangan" json:"pemeriksaan_susunan_kepala_keterangan"`
	PemeriksaanSusunanWajah                          string     `gorm:"column:pemeriksaan_susunan_wajah" json:"pemeriksaan_susunan_wajah"`
	PemeriksaanSusunanWajahKeterangan                string     `gorm:"column:pemeriksaan_susunan_wajah_keterangan" json:"pemeriksaan_susunan_wajah_keterangan"`
	PemeriksaanSusunanLeher                          string     `gorm:"column:pemeriksaan_susunan_leher" json:"pemeriksaan_susunan_leher"`
	PemeriksaanSusunanKejang                         string     `gorm:"column:pemeriksaan_susunan_kejang" json:"pemeriksaan_susunan_kejang"`
	PemeriksaanSusunanKejangKeterangan               string     `gorm:"column:pemeriksaan_susunan_kejang_keterangan" json:"pemeriksaan_susunan_kejang_keterangan"`
	PemeriksaanSusunanSensorik                       string     `gorm:"column:pemeriksaan_susunan_sensorik" json:"pemeriksaan_susunan_sensorik"`
	PemeriksaanKardiovaskulerDenyutNadi              string     `gorm:"column:pemeriksaan_kardiovaskuler_denyut_nadi" json:"pemeriksaan_kardiovaskuler_denyut_nadi"`
	PemeriksaanKardiovaskulerSirkulasi               string     `gorm:"column:pemeriksaan_kardiovaskuler_sirkulasi" json:"pemeriksaan_kardiovaskuler_sirkulasi"`
	PemeriksaanKardiovaskulerSirkulasiKeterangan     string     `gorm:"column:pemeriksaan_kardiovaskuler_sirkulasi_keterangan" json:"pemeriksaan_kardiovaskuler_sirkulasi_keterangan"`
	PemeriksaanKardiovaskulerPulsasi                 string     `gorm:"column:pemeriksaan_kardiovaskuler_pulsasi" json:"pemeriksaan_kardiovaskuler_pulsasi"`
	PemeriksaanRespirasiPolaNafas                    string     `gorm:"column:pemeriksaan_respirasi_pola_nafas" json:"pemeriksaan_respirasi_pola_nafas"`
	PemeriksaanRespirasiRetraksi                     string     `gorm:"column:pemeriksaan_respirasi_retraksi" json:"pemeriksaan_respirasi_retraksi"`
	PemeriksaanRespirasiSuaraNafas                   string     `gorm:"column:pemeriksaan_respirasi_suara_nafas" json:"pemeriksaan_respirasi_suara_nafas"`
	PemeriksaanRespirasiVolumePernafasan             string     `gorm:"column:pemeriksaan_respirasi_volume_pernafasan" json:"pemeriksaan_respirasi_volume_pernafasan"`
	PemeriksaanRespirasiJenisPernafasan              string     `gorm:"column:pemeriksaan_respirasi_jenis_pernafasan" json:"pemeriksaan_respirasi_jenis_pernafasan"`
	PemeriksaanRespirasiJenisPernafasanKeterangan    string     `gorm:"column:pemeriksaan_respirasi_jenis_pernafasan_keterangan" json:"pemeriksaan_respirasi_jenis_pernafasan_keterangan"`
	PemeriksaanRespirasiIramaNafas                   string     `gorm:"column:pemeriksaan_respirasi_irama_nafas" json:"pemeriksaan_respirasi_irama_nafas"`
	PemeriksaanRespirasiBatuk                        string     `gorm:"column:pemeriksaan_respirasi_batuk" json:"pemeriksaan_respirasi_batuk"`
	PemeriksaanGastrointestinalMulut                 string     `gorm:"column:pemeriksaan_gastrointestinal_mulut" json:"pemeriksaan_gastrointestinal_mulut"`
	PemeriksaanGastrointestinalMulutKeterangan       string     `gorm:"column:pemeriksaan_gastrointestinal_mulut_keterangan" json:"pemeriksaan_gastrointestinal_mulut_keterangan"`
	PemeriksaanGastrointestinalGigi                  string     `gorm:"column:pemeriksaan_gastrointestinal_gigi" json:"pemeriksaan_gastrointestinal_gigi"`
	PemeriksaanGastrointestinalGigiKeterangan        string     `gorm:"column:pemeriksaan_gastrointestinal_gigi_keterangan" json:"pemeriksaan_gastrointestinal_gigi_keterangan"`
	PemeriksaanGastrointestinalLidah                 string     `gorm:"column:pemeriksaan_gastrointestinal_lidah" json:"pemeriksaan_gastrointestinal_lidah"`
	PemeriksaanGastrointestinalLidahKeterangan       string     `gorm:"column:pemeriksaan_gastrointestinal_lidah_keterangan" json:"pemeriksaan_gastrointestinal_lidah_keterangan"`
	PemeriksaanGastrointestinalTenggorokan           string     `gorm:"column:pemeriksaan_gastrointestinal_tenggorokan" json:"pemeriksaan_gastrointestinal_tenggorokan"`
	PemeriksaanGastrointestinalTenggorokanKeterangan string     `gorm:"column:pemeriksaan_gastrointestinal_tenggorokan_keterangan" json:"pemeriksaan_gastrointestinal_tenggorokan_keterangan"`
	PemeriksaanGastrointestinalAbdomen               string     `gorm:"column:pemeriksaan_gastrointestinal_abdomen" json:"pemeriksaan_gastrointestinal_abdomen"`
	PemeriksaanGastrointestinalAbdomenKeterangan     string     `gorm:"column:pemeriksaan_gastrointestinal_abdomen_keterangan" json:"pemeriksaan_gastrointestinal_abdomen_keterangan"`
	PemeriksaanGastrointestinalPeistatikUsus         string     `gorm:"column:pemeriksaan_gastrointestinal_peistatik_usus" json:"pemeriksaan_gastrointestinal_peistatik_usus"`
	PemeriksaanGastrointestinalAnus                  string     `gorm:"column:pemeriksaan_gastrointestinal_anus" json:"pemeriksaan_gastrointestinal_anus"`
	PemeriksaanNeurologiPengelihatan                 string     `gorm:"column:pemeriksaan_neurologi_pengelihatan" json:"pemeriksaan_neurologi_pengelihatan"`
	PemeriksaanNeurologiPengelihatanKeterangan       string     `gorm:"column:pemeriksaan_neurologi_pengelihatan_keterangan" json:"pemeriksaan_neurologi_pengelihatan_keterangan"`
	PemeriksaanNeurologiAlatBantuPenglihatan         string     `gorm:"column:pemeriksaan_neurologi_alat_bantu_penglihatan" json:"pemeriksaan_neurologi_alat_bantu_penglihatan"`
	PemeriksaanNeurologiPendengaran                  string     `gorm:"column:pemeriksaan_neurologi_pendengaran" json:"pemeriksaan_neurologi_pendengaran"`
	PemeriksaanNeurologiBicara                       string     `gorm:"column:pemeriksaan_neurologi_bicara" json:"pemeriksaan_neurologi_bicara"`
	PemeriksaanNeurologiBicaraKeterangan             string     `gorm:"column:pemeriksaan_neurologi_bicara_keterangan" json:"pemeriksaan_neurologi_bicara_keterangan"`
	PemeriksaanNeurologiSensorik                     string     `gorm:"column:pemeriksaan_neurologi_sensorik" json:"pemeriksaan_neurologi_sensorik"`
	PemeriksaanNeurologiMotorik                      string     `gorm:"column:pemeriksaan_neurologi_motorik" json:"pemeriksaan_neurologi_motorik"`
	PemeriksaanNeurologiKekuatanOtot                 string     `gorm:"column:pemeriksaan_neurologi_kekuatan_otot" json:"pemeriksaan_neurologi_kekuatan_otot"`
	PemeriksaanIntegumentWarnakulit                  string     `gorm:"column:pemeriksaan_integument_warnakulit" json:"pemeriksaan_integument_warnakulit"`
	PemeriksaanIntegumentTurgor                      string     `gorm:"column:pemeriksaan_integument_turgor" json:"pemeriksaan_integument_turgor"`
	PemeriksaanIntegumentKulit                       string     `gorm:"column:pemeriksaan_integument_kulit" json:"pemeriksaan_integument_kulit"`
	PemeriksaanIntegumentDekubitas                   string     `gorm:"column:pemeriksaan_integument_dekubitas" json:"pemeriksaan_integument_dekubitas"`
	PemeriksaanMuskuloskletalPergerakanSendi         string     `gorm:"column:pemeriksaan_muskuloskletal_pergerakan_sendi" json:"pemeriksaan_muskuloskletal_pergerakan_sendi"`
	PemeriksaanMuskuloskletalKekauatanOtot           string     `gorm:"column:pemeriksaan_muskuloskletal_kekauatan_otot" json:"pemeriksaan_muskuloskletal_kekauatan_otot"`
	PemeriksaanMuskuloskletalNyeriSendi              string     `gorm:"column:pemeriksaan_muskuloskletal_nyeri_sendi" json:"pemeriksaan_muskuloskletal_nyeri_sendi"`
	PemeriksaanMuskuloskletalNyeriSendiKeterangan    string     `gorm:"column:pemeriksaan_muskuloskletal_nyeri_sendi_keterangan" json:"pemeriksaan_muskuloskletal_nyeri_sendi_keterangan"`
	PemeriksaanMuskuloskletalOedema                  string     `gorm:"column:pemeriksaan_muskuloskletal_oedema" json:"pemeriksaan_muskuloskletal_oedema"`
	PemeriksaanMuskuloskletalOedemaKeterangan        string     `gorm:"column:pemeriksaan_muskuloskletal_oedema_keterangan" json:"pemeriksaan_muskuloskletal_oedema_keterangan"`
	PemeriksaanMuskuloskletalFraktur                 string     `gorm:"column:pemeriksaan_muskuloskletal_fraktur" json:"pemeriksaan_muskuloskletal_fraktur"`
	PemeriksaanMuskuloskletalFrakturKeterangan       string     `gorm:"column:pemeriksaan_muskuloskletal_fraktur_keterangan" json:"pemeriksaan_muskuloskletal_fraktur_keterangan"`
	PemeriksaanEliminasiBabFrekuensiJumlah           string     `gorm:"column:pemeriksaan_eliminasi_bab_frekuensi_jumlah" json:"pemeriksaan_eliminasi_bab_frekuensi_jumlah"`
	PemeriksaanEliminasiBabFrekuensiDurasi           string     `gorm:"column:pemeriksaan_eliminasi_bab_frekuensi_durasi" json:"pemeriksaan_eliminasi_bab_frekuensi_durasi"`
	PemeriksaanEliminasiBabKonsistensi               string     `gorm:"column:pemeriksaan_eliminasi_bab_konsistensi" json:"pemeriksaan_eliminasi_bab_konsistensi"`
	PemeriksaanEliminasiBabWarna                     string     `gorm:"column:pemeriksaan_eliminasi_bab_warna" json:"pemeriksaan_eliminasi_bab_warna"`
	PemeriksaanEliminasiBakFrekuensiJumlah           string     `gorm:"column:pemeriksaan_eliminasi_bak_frekuensi_jumlah" json:"pemeriksaan_eliminasi_bak_frekuensi_jumlah"`
	PemeriksaanEliminasiBakFrekuensiDurasi           string     `gorm:"column:pemeriksaan_eliminasi_bak_frekuensi_durasi" json:"pemeriksaan_eliminasi_bak_frekuensi_durasi"`
	PemeriksaanEliminasiBakWarna                     string     `gorm:"column:pemeriksaan_eliminasi_bak_warna" json:"pemeriksaan_eliminasi_bak_warna"`
	PemeriksaanEliminasiBakLainlain                  string     `gorm:"column:pemeriksaan_eliminasi_bak_lainlain" json:"pemeriksaan_eliminasi_bak_lainlain"`
	PolaAktifitasMakanminum                          string     `gorm:"column:pola_aktifitas_makanminum" json:"pola_aktifitas_makanminum"`
	PolaAktifitasMandi                               string     `gorm:"column:pola_aktifitas_mandi" json:"pola_aktifitas_mandi"`
	PolaAktifitasEliminasi                           string     `gorm:"column:pola_aktifitas_eliminasi" json:"pola_aktifitas_eliminasi"`
	PolaAktifitasBerpakaian                          string     `gorm:"column:pola_aktifitas_berpakaian" json:"pola_aktifitas_berpakaian"`
	PolaAktifitasBerpindah                           string     `gorm:"column:pola_aktifitas_berpindah" json:"pola_aktifitas_berpindah"`
	PolaNutrisiFrekuesiMakan                         string     `gorm:"column:pola_nutrisi_frekuesi_makan" json:"pola_nutrisi_frekuesi_makan"`
	PolaNutrisiJenisMakanan                          string     `gorm:"column:pola_nutrisi_jenis_makanan" json:"pola_nutrisi_jenis_makanan"`
	PolaNutrisiPorsiMakan                            string     `gorm:"column:pola_nutrisi_porsi_makan" json:"pola_nutrisi_porsi_makan"`
	PolaTidurLamaTidur                               string     `gorm:"column:pola_tidur_lama_tidur" json:"pola_tidur_lama_tidur"`
	PolaTidurGangguan                                string     `gorm:"column:pola_tidur_gangguan" json:"pola_tidur_gangguan"`
	PengkajianFungsiKemampuanSehari                  string     `gorm:"column:pengkajian_fungsi_kemampuan_sehari" json:"pengkajian_fungsi_kemampuan_sehari"`
	PengkajianFungsiAktifitas                        string     `gorm:"column:pengkajian_fungsi_aktifitas" json:"pengkajian_fungsi_aktifitas"`
	PengkajianFungsiBerjalan                         string     `gorm:"column:pengkajian_fungsi_berjalan" json:"pengkajian_fungsi_berjalan"`
	PengkajianFungsiBerjalanKeterangan               string     `gorm:"column:pengkajian_fungsi_berjalan_keterangan" json:"pengkajian_fungsi_berjalan_keterangan"`
	PengkajianFungsiAmbulasi                         string     `gorm:"column:pengkajian_fungsi_ambulasi" json:"pengkajian_fungsi_ambulasi"`
	PengkajianFungsiEkstrimitasAtas                  string     `gorm:"column:pengkajian_fungsi_ekstrimitas_atas" json:"pengkajian_fungsi_ekstrimitas_atas"`
	PengkajianFungsiEkstrimitasAtasKeterangan        string     `gorm:"column:pengkajian_fungsi_ekstrimitas_atas_keterangan" json:"pengkajian_fungsi_ekstrimitas_atas_keterangan"`
	PengkajianFungsiEkstrimitasBawah                 string     `gorm:"column:pengkajian_fungsi_ekstrimitas_bawah" json:"pengkajian_fungsi_ekstrimitas_bawah"`
	PengkajianFungsiEkstrimitasBawahKeterangan       string     `gorm:"column:pengkajian_fungsi_ekstrimitas_bawah_keterangan" json:"pengkajian_fungsi_ekstrimitas_bawah_keterangan"`
	PengkajianFungsiMenggenggam                      string     `gorm:"column:pengkajian_fungsi_menggenggam" json:"pengkajian_fungsi_menggenggam"`
	PengkajianFungsiMenggenggamKeterangan            string     `gorm:"column:pengkajian_fungsi_menggenggam_keterangan" json:"pengkajian_fungsi_menggenggam_keterangan"`
	PengkajianFungsiKoordinasi                       string     `gorm:"column:pengkajian_fungsi_koordinasi" json:"pengkajian_fungsi_koordinasi"`
	PengkajianFungsiKoordinasiKeterangan             string     `gorm:"column:pengkajian_fungsi_koordinasi_keterangan" json:"pengkajian_fungsi_koordinasi_keterangan"`
	PengkajianFungsiKesimpulan                       string     `gorm:"column:pengkajian_fungsi_kesimpulan" json:"pengkajian_fungsi_kesimpulan"`
	RiwayatPsikoKondisiPsiko                         string     `gorm:"column:riwayat_psiko_kondisi_psiko" json:"riwayat_psiko_kondisi_psiko"`
	RiwayatPsikoGangguanJiwa                         string     `gorm:"column:riwayat_psiko_gangguan_jiwa" json:"riwayat_psiko_gangguan_jiwa"`
	RiwayatPsikoPerilaku                             string     `gorm:"column:riwayat_psiko_perilaku" json:"riwayat_psiko_perilaku"`
	RiwayatPsikoPerilakuKeterangan                   string     `gorm:"column:riwayat_psiko_perilaku_keterangan" json:"riwayat_psiko_perilaku_keterangan"`
	RiwayatPsikoHubunganKeluarga                     string     `gorm:"column:riwayat_psiko_hubungan_keluarga" json:"riwayat_psiko_hubungan_keluarga"`
	RiwayatPsikoTinggal                              string     `gorm:"column:riwayat_psiko_tinggal" json:"riwayat_psiko_tinggal"`
	RiwayatPsikoTinggalKeterangan                    string     `gorm:"column:riwayat_psiko_tinggal_keterangan" json:"riwayat_psiko_tinggal_keterangan"`
	RiwayatPsikoNilaiKepercayaan                     string     `gorm:"column:riwayat_psiko_nilai_kepercayaan" json:"riwayat_psiko_nilai_kepercayaan"`
	RiwayatPsikoNilaiKepercayaanKeterangan           string     `gorm:"column:riwayat_psiko_nilai_kepercayaan_keterangan" json:"riwayat_psiko_nilai_kepercayaan_keterangan"`
	RiwayatPsikoPendidikanPj                         string     `gorm:"column:riwayat_psiko_pendidikan_pj" json:"riwayat_psiko_pendidikan_pj"`
	RiwayatPsikoEdukasiDiberikan                     string     `gorm:"column:riwayat_psiko_edukasi_diberikan" json:"riwayat_psiko_edukasi_diberikan"`
	RiwayatPsikoEdukasiDiberikanKeterangan           string     `gorm:"column:riwayat_psiko_edukasi_diberikan_keterangan" json:"riwayat_psiko_edukasi_diberikan_keterangan"`
	PenilaianNyeri                                   string     `gorm:"column:penilaian_nyeri" json:"penilaian_nyeri"`
	PenilaianNyeriPenyebab                           string     `gorm:"column:penilaian_nyeri_penyebab" json:"penilaian_nyeri_penyebab"`
	PenilaianNyeriKetPenyebab                        string     `gorm:"column:penilaian_nyeri_ket_penyebab" json:"penilaian_nyeri_ket_penyebab"`
	PenilaianNyeriKualitas                           string     `gorm:"column:penilaian_nyeri_kualitas" json:"penilaian_nyeri_kualitas"`
	PenilaianNyeriKetKualitas                        string     `gorm:"column:penilaian_nyeri_ket_kualitas" json:"penilaian_nyeri_ket_kualitas"`
	PenilaianNyeriLokasi                             string     `gorm:"column:penilaian_nyeri_lokasi" json:"penilaian_nyeri_lokasi"`
	PenilaianNyeriMenyebar                           string     `gorm:"column:penilaian_nyeri_menyebar" json:"penilaian_nyeri_menyebar"`
	PenilaianNyeriSkala                              string     `gorm:"column:penilaian_nyeri_skala" json:"penilaian_nyeri_skala"`
	PenilaianNyeriWaktu                              string     `gorm:"column:penilaian_nyeri_waktu" json:"penilaian_nyeri_waktu"`
	PenilaianNyeriHilang                             string     `gorm:"column:penilaian_nyeri_hilang" json:"penilaian_nyeri_hilang"`
	PenilaianNyeriKetHilang                          string     `gorm:"column:penilaian_nyeri_ket_hilang" json:"penilaian_nyeri_ket_hilang"`
	PenilaianNyeriDiberitahukanDokter                string     `gorm:"column:penilaian_nyeri_diberitahukan_dokter" json:"penilaian_nyeri_diberitahukan_dokter"`
	PenilaianNyeriJamDiberitahukanDokter             string     `gorm:"column:penilaian_nyeri_jam_diberitahukan_dokter" json:"penilaian_nyeri_jam_diberitahukan_dokter"`
	PenilaianJatuhmorseSkala1                        *string    `gorm:"column:penilaian_jatuhmorse_skala1" json:"penilaian_jatuhmorse_skala1"`
	PenilaianJatuhmorseNilai1                        *int       `gorm:"column:penilaian_jatuhmorse_nilai1" json:"penilaian_jatuhmorse_nilai1"`
	PenilaianJatuhmorseSkala2                        *string    `gorm:"column:penilaian_jatuhmorse_skala2" json:"penilaian_jatuhmorse_skala2"`
	PenilaianJatuhmorseNilai2                        *int       `gorm:"column:penilaian_jatuhmorse_nilai2" json:"penilaian_jatuhmorse_nilai2"`
	PenilaianJatuhmorseSkala3                        *string    `gorm:"column:penilaian_jatuhmorse_skala3" json:"penilaian_jatuhmorse_skala3"`
	PenilaianJatuhmorseNilai3                        *int       `gorm:"column:penilaian_jatuhmorse_nilai3" json:"penilaian_jatuhmorse_nilai3"`
	PenilaianJatuhmorseSkala4                        *string    `gorm:"column:penilaian_jatuhmorse_skala4" json:"penilaian_jatuhmorse_skala4"`
	PenilaianJatuhmorseNilai4                        *int       `gorm:"column:penilaian_jatuhmorse_nilai4" json:"penilaian_jatuhmorse_nilai4"`
	PenilaianJatuhmorseSkala5                        *string    `gorm:"column:penilaian_jatuhmorse_skala5" json:"penilaian_jatuhmorse_skala5"`
	PenilaianJatuhmorseNilai5                        *int       `gorm:"column:penilaian_jatuhmorse_nilai5" json:"penilaian_jatuhmorse_nilai5"`
	PenilaianJatuhmorseSkala6                        *string    `gorm:"column:penilaian_jatuhmorse_skala6" json:"penilaian_jatuhmorse_skala6"`
	PenilaianJatuhmorseNilai6                        *int       `gorm:"column:penilaian_jatuhmorse_nilai6" json:"penilaian_jatuhmorse_nilai6"`
	PenilaianJatuhmorseTotalnilai                    *int       `gorm:"column:penilaian_jatuhmorse_totalnilai" json:"penilaian_jatuhmorse_totalnilai"`
	PenilaianJatuhsydneySkala1                       *string    `gorm:"column:penilaian_jatuhsydney_skala1" json:"penilaian_jatuhsydney_skala1"`
	PenilaianJatuhsydneyNilai1                       *int       `gorm:"column:penilaian_jatuhsydney_nilai1" json:"penilaian_jatuhsydney_nilai1"`
	PenilaianJatuhsydneySkala2                       *string    `gorm:"column:penilaian_jatuhsydney_skala2" json:"penilaian_jatuhsydney_skala2"`
	PenilaianJatuhsydneyNilai2                       *int       `gorm:"column:penilaian_jatuhsydney_nilai2" json:"penilaian_jatuhsydney_nilai2"`
	PenilaianJatuhsydneySkala3                       *string    `gorm:"column:penilaian_jatuhsydney_skala3" json:"penilaian_jatuhsydney_skala3"`
	PenilaianJatuhsydneyNilai3                       *int       `gorm:"column:penilaian_jatuhsydney_nilai3" json:"penilaian_jatuhsydney_nilai3"`
	PenilaianJatuhsydneySkala4                       *string    `gorm:"column:penilaian_jatuhsydney_skala4" json:"penilaian_jatuhsydney_skala4"`
	PenilaianJatuhsydneyNilai4                       *int       `gorm:"column:penilaian_jatuhsydney_nilai4" json:"penilaian_jatuhsydney_nilai4"`
	PenilaianJatuhsydneySkala5                       *string    `gorm:"column:penilaian_jatuhsydney_skala5" json:"penilaian_jatuhsydney_skala5"`
	PenilaianJatuhsydneyNilai5                       *int       `gorm:"column:penilaian_jatuhsydney_nilai5" json:"penilaian_jatuhsydney_nilai5"`
	PenilaianJatuhsydneySkala6                       *string    `gorm:"column:penilaian_jatuhsydney_skala6" json:"penilaian_jatuhsydney_skala6"`
	PenilaianJatuhsydneyNilai6                       *int       `gorm:"column:penilaian_jatuhsydney_nilai6" json:"penilaian_jatuhsydney_nilai6"`
	PenilaianJatuhsydneySkala7                       *string    `gorm:"column:penilaian_jatuhsydney_skala7" json:"penilaian_jatuhsydney_skala7"`
	PenilaianJatuhsydneyNilai7                       *int       `gorm:"column:penilaian_jatuhsydney_nilai7" json:"penilaian_jatuhsydney_nilai7"`
	PenilaianJatuhsydneySkala8                       *string    `gorm:"column:penilaian_jatuhsydney_skala8" json:"penilaian_jatuhsydney_skala8"`
	PenilaianJatuhsydneyNilai8                       *int       `gorm:"column:penilaian_jatuhsydney_nilai8" json:"penilaian_jatuhsydney_nilai8"`
	PenilaianJatuhsydneySkala9                       *string    `gorm:"column:penilaian_jatuhsydney_skala9" json:"penilaian_jatuhsydney_skala9"`
	PenilaianJatuhsydneyNilai9                       *int       `gorm:"column:penilaian_jatuhsydney_nilai9" json:"penilaian_jatuhsydney_nilai9"`
	PenilaianJatuhsydneySkala10                      *string    `gorm:"column:penilaian_jatuhsydney_skala10" json:"penilaian_jatuhsydney_skala10"`
	PenilaianJatuhsydneyNilai10                      *int       `gorm:"column:penilaian_jatuhsydney_nilai10" json:"penilaian_jatuhsydney_nilai10"`
	PenilaianJatuhsydneySkala11                      *string    `gorm:"column:penilaian_jatuhsydney_skala11" json:"penilaian_jatuhsydney_skala11"`
	PenilaianJatuhsydneyNilai11                      *int       `gorm:"column:penilaian_jatuhsydney_nilai11" json:"penilaian_jatuhsydney_nilai11"`
	PenilaianJatuhsydneyTotalnilai                   *int       `gorm:"column:penilaian_jatuhsydney_totalnilai" json:"penilaian_jatuhsydney_totalnilai"`
	SkriningGizi1                                    *string    `gorm:"column:skrining_gizi1" json:"skrining_gizi1"`
	NilaiGizi1                                       *int       `gorm:"column:nilai_gizi1" json:"nilai_gizi1"`
	SkriningGizi2                                    *string    `gorm:"column:skrining_gizi2" json:"skrining_gizi2"`
	NilaiGizi2                                       *int       `gorm:"column:nilai_gizi2" json:"nilai_gizi2"`
	NilaiTotalGizi                                   *float64   `gorm:"column:nilai_total_gizi" json:"nilai_total_gizi"`
	SkriningGiziDiagnosaKhusus                       *string    `gorm:"column:skrining_gizi_diagnosa_khusus" json:"skrining_gizi_diagnosa_khusus"`
	SkriningGiziKetDiagnosaKhusus                    *string    `gorm:"column:skrining_gizi_ket_diagnosa_khusus" json:"skrining_gizi_ket_diagnosa_khusus"`
	SkriningGiziDiketahuiDietisen                    *string    `gorm:"column:skrining_gizi_diketahui_dietisen" json:"skrining_gizi_diketahui_dietisen"`
	SkriningGiziJamDiketahuiDietisen                 *string    `gorm:"column:skrining_gizi_jam_diketahui_dietisen" json:"skrining_gizi_jam_diketahui_dietisen"`
	Rencana                                          *string    `gorm:"column:rencana" json:"rencana"`
	Nip1                                             string     `gorm:"column:nip1" json:"nip1"`
	Nip2                                             string     `gorm:"column:nip2" json:"nip2"`
	KdDokter                                         string     `gorm:"column:kd_dokter" json:"kd_dokter"`
}

func (PenilaianAwalKeperawatanRanap) TableName() string {
	return "penilaian_awal_keperawatan_ranap"
}
