package rekammedis

import "time"

// PenilaianAwalKeperawatanRalanPsikiatri tabel `penilaian_awal_keperawatan_ralan_psikiatri` (penilaian awal keperawatan ralan psikiatri, RMPenilaianAwalKeperawatanRalanPsikiatri).
type PenilaianAwalKeperawatanRalanPsikiatri struct {
	NoRawat                     string     `gorm:"column:no_rawat;primaryKey;autoIncrement:false" json:"no_rawat"`
	Tanggal                     *time.Time `gorm:"column:tanggal" json:"tanggal"`
	Informasi                   string     `gorm:"column:informasi" json:"informasi"`
	KeluhanUtama                string     `gorm:"column:keluhan_utama" json:"keluhan_utama"`
	RkdSakitSejak               string     `gorm:"column:rkd_sakit_sejak" json:"rkd_sakit_sejak"`
	RkdKeluhan                  string     `gorm:"column:rkd_keluhan" json:"rkd_keluhan"`
	RkdBerobat                  string     `gorm:"column:rkd_berobat" json:"rkd_berobat"`
	RkdHasilPengobatan          string     `gorm:"column:rkd_hasil_pengobatan" json:"rkd_hasil_pengobatan"`
	FpPutusObat                 string     `gorm:"column:fp_putus_obat" json:"fp_putus_obat"`
	KetPutusObat                string     `gorm:"column:ket_putus_obat" json:"ket_putus_obat"`
	FpEkonomi                   string     `gorm:"column:fp_ekonomi" json:"fp_ekonomi"`
	KetMasalahEkonomi           string     `gorm:"column:ket_masalah_ekonomi" json:"ket_masalah_ekonomi"`
	FpMasalahFisik              string     `gorm:"column:fp_masalah_fisik" json:"fp_masalah_fisik"`
	KetMasalahFisik             string     `gorm:"column:ket_masalah_fisik" json:"ket_masalah_fisik"`
	FpMasalahPsikososial        string     `gorm:"column:fp_masalah_psikososial" json:"fp_masalah_psikososial"`
	KetMasalahPsikososial       string     `gorm:"column:ket_masalah_psikososial" json:"ket_masalah_psikososial"`
	RhKeluarga                  string     `gorm:"column:rh_keluarga" json:"rh_keluarga"`
	KetRhKeluarga               string     `gorm:"column:ket_rh_keluarga" json:"ket_rh_keluarga"`
	ResikoBunuhDiri             string     `gorm:"column:resiko_bunuh_diri" json:"resiko_bunuh_diri"`
	RbdIde                      string     `gorm:"column:rbd_ide" json:"rbd_ide"`
	KetRbdIde                   string     `gorm:"column:ket_rbd_ide" json:"ket_rbd_ide"`
	RbdRencana                  string     `gorm:"column:rbd_rencana" json:"rbd_rencana"`
	KetRbdRencana               string     `gorm:"column:ket_rbd_rencana" json:"ket_rbd_rencana"`
	RbdAlat                     string     `gorm:"column:rbd_alat" json:"rbd_alat"`
	KetRbdAlat                  string     `gorm:"column:ket_rbd_alat" json:"ket_rbd_alat"`
	RbdPercobaan                string     `gorm:"column:rbd_percobaan" json:"rbd_percobaan"`
	KetRbdPercobaan             string     `gorm:"column:ket_rbd_percobaan" json:"ket_rbd_percobaan"`
	RbdKeinginan                string     `gorm:"column:rbd_keinginan" json:"rbd_keinginan"`
	KetRbdKeinginan             string     `gorm:"column:ket_rbd_keinginan" json:"ket_rbd_keinginan"`
	RpoPenggunaan               string     `gorm:"column:rpo_penggunaan" json:"rpo_penggunaan"`
	KetRpoPenggunaan            string     `gorm:"column:ket_rpo_penggunaan" json:"ket_rpo_penggunaan"`
	RpoEfekSamping              string     `gorm:"column:rpo_efek_samping" json:"rpo_efek_samping"`
	KetRpoEfekSamping           string     `gorm:"column:ket_rpo_efek_samping" json:"ket_rpo_efek_samping"`
	RpoNapza                    string     `gorm:"column:rpo_napza" json:"rpo_napza"`
	KetRpoNapza                 string     `gorm:"column:ket_rpo_napza" json:"ket_rpo_napza"`
	KetLamaPemakaian            string     `gorm:"column:ket_lama_pemakaian" json:"ket_lama_pemakaian"`
	KetCaraPemakaian            string     `gorm:"column:ket_cara_pemakaian" json:"ket_cara_pemakaian"`
	KetLatarBelakangPemakaian   string     `gorm:"column:ket_latar_belakang_pemakaian" json:"ket_latar_belakang_pemakaian"`
	RpoPenggunaanObatLainnya    string     `gorm:"column:rpo_penggunaan_obat_lainnya" json:"rpo_penggunaan_obat_lainnya"`
	KetPenggunaanObatLainnya    string     `gorm:"column:ket_penggunaan_obat_lainnya" json:"ket_penggunaan_obat_lainnya"`
	KetAlasanPenggunaan         string     `gorm:"column:ket_alasan_penggunaan" json:"ket_alasan_penggunaan"`
	RpoAlergiObat               string     `gorm:"column:rpo_alergi_obat" json:"rpo_alergi_obat"`
	KetAlergiObat               string     `gorm:"column:ket_alergi_obat" json:"ket_alergi_obat"`
	RpoMerokok                  string     `gorm:"column:rpo_merokok" json:"rpo_merokok"`
	KetMerokok                  string     `gorm:"column:ket_merokok" json:"ket_merokok"`
	RpoMinumKopi                string     `gorm:"column:rpo_minum_kopi" json:"rpo_minum_kopi"`
	KetMinumKopi                string     `gorm:"column:ket_minum_kopi" json:"ket_minum_kopi"`
	Td                          string     `gorm:"column:td" json:"td"`
	Nadi                        string     `gorm:"column:nadi" json:"nadi"`
	Gcs                         string     `gorm:"column:gcs" json:"gcs"`
	Rr                          string     `gorm:"column:rr" json:"rr"`
	Suhu                        string     `gorm:"column:suhu" json:"suhu"`
	PfKeluhanFisik              string     `gorm:"column:pf_keluhan_fisik" json:"pf_keluhan_fisik"`
	KetKeluhanFisik             string     `gorm:"column:ket_keluhan_fisik" json:"ket_keluhan_fisik"`
	SkalaNyeri                  string     `gorm:"column:skala_nyeri" json:"skala_nyeri"`
	Durasi                      string     `gorm:"column:durasi" json:"durasi"`
	Nyeri                       string     `gorm:"column:nyeri" json:"nyeri"`
	Provokes                    string     `gorm:"column:provokes" json:"provokes"`
	KetProvokes                 string     `gorm:"column:ket_provokes" json:"ket_provokes"`
	Quality                     string     `gorm:"column:quality" json:"quality"`
	KetQuality                  string     `gorm:"column:ket_quality" json:"ket_quality"`
	Lokasi                      string     `gorm:"column:lokasi" json:"lokasi"`
	Menyebar                    string     `gorm:"column:menyebar" json:"menyebar"`
	PadaDokter                  string     `gorm:"column:pada_dokter" json:"pada_dokter"`
	KetDokter                   string     `gorm:"column:ket_dokter" json:"ket_dokter"`
	NyeriHilang                 string     `gorm:"column:nyeri_hilang" json:"nyeri_hilang"`
	KetNyeri                    string     `gorm:"column:ket_nyeri" json:"ket_nyeri"`
	Bb                          string     `gorm:"column:bb" json:"bb"`
	Tb                          string     `gorm:"column:tb" json:"tb"`
	Bmi                         string     `gorm:"column:bmi" json:"bmi"`
	LaporStatusNutrisi          string     `gorm:"column:lapor_status_nutrisi" json:"lapor_status_nutrisi"`
	KetLaporStatusNutrisi       string     `gorm:"column:ket_lapor_status_nutrisi" json:"ket_lapor_status_nutrisi"`
	Sg1                         string     `gorm:"column:sg1" json:"sg1"`
	Nilai1                      string     `gorm:"column:nilai1" json:"nilai1"`
	Sg2                         string     `gorm:"column:sg2" json:"sg2"`
	Nilai2                      string     `gorm:"column:nilai2" json:"nilai2"`
	TotalHasil                  int        `gorm:"column:total_hasil" json:"total_hasil"`
	Resikojatuh                 string     `gorm:"column:resikojatuh" json:"resikojatuh"`
	Bjm                         string     `gorm:"column:bjm" json:"bjm"`
	Msa                         string     `gorm:"column:msa" json:"msa"`
	Hasil                       string     `gorm:"column:hasil" json:"hasil"`
	Lapor                       string     `gorm:"column:lapor" json:"lapor"`
	KetLapor                    string     `gorm:"column:ket_lapor" json:"ket_lapor"`
	AdlMandi                    string     `gorm:"column:adl_mandi" json:"adl_mandi"`
	AdlBerpakaian               string     `gorm:"column:adl_berpakaian" json:"adl_berpakaian"`
	AdlMakan                    string     `gorm:"column:adl_makan" json:"adl_makan"`
	AdlBak                      string     `gorm:"column:adl_bak" json:"adl_bak"`
	AdlBab                      string     `gorm:"column:adl_bab" json:"adl_bab"`
	AdlHobi                     string     `gorm:"column:adl_hobi" json:"adl_hobi"`
	KetAdlHobi                  string     `gorm:"column:ket_adl_hobi" json:"ket_adl_hobi"`
	AdlSosialisasi              string     `gorm:"column:adl_sosialisasi" json:"adl_sosialisasi"`
	KetAdlSosialisasi           string     `gorm:"column:ket_adl_sosialisasi" json:"ket_adl_sosialisasi"`
	AdlKegiatan                 string     `gorm:"column:adl_kegiatan" json:"adl_kegiatan"`
	KetAdlKegiatan              string     `gorm:"column:ket_adl_kegiatan" json:"ket_adl_kegiatan"`
	SkPenampilan                string     `gorm:"column:sk_penampilan" json:"sk_penampilan"`
	SkAlamPerasaan              string     `gorm:"column:sk_alam_perasaan" json:"sk_alam_perasaan"`
	SkPembicaraan               string     `gorm:"column:sk_pembicaraan" json:"sk_pembicaraan"`
	SkAfek                      string     `gorm:"column:sk_afek" json:"sk_afek"`
	SkAktifitasMotorik          string     `gorm:"column:sk_aktifitas_motorik" json:"sk_aktifitas_motorik"`
	SkGangguanRingan            string     `gorm:"column:sk_gangguan_ringan" json:"sk_gangguan_ringan"`
	SkProsesPikir               string     `gorm:"column:sk_proses_pikir" json:"sk_proses_pikir"`
	SkOrientasi                 string     `gorm:"column:sk_orientasi" json:"sk_orientasi"`
	SkTingkatKesadaranOrientasi string     `gorm:"column:sk_tingkat_kesadaran_orientasi" json:"sk_tingkat_kesadaran_orientasi"`
	SkMemori                    string     `gorm:"column:sk_memori" json:"sk_memori"`
	SkInteraksi                 string     `gorm:"column:sk_interaksi" json:"sk_interaksi"`
	SkKonsentrasi               string     `gorm:"column:sk_konsentrasi" json:"sk_konsentrasi"`
	SkPersepsi                  string     `gorm:"column:sk_persepsi" json:"sk_persepsi"`
	KetSkPersepsi               string     `gorm:"column:ket_sk_persepsi" json:"ket_sk_persepsi"`
	SkIsiPikir                  string     `gorm:"column:sk_isi_pikir" json:"sk_isi_pikir"`
	SkWaham                     string     `gorm:"column:sk_waham" json:"sk_waham"`
	KetSkWaham                  string     `gorm:"column:ket_sk_waham" json:"ket_sk_waham"`
	SkDayaTilikDiri             string     `gorm:"column:sk_daya_tilik_diri" json:"sk_daya_tilik_diri"`
	KetSkDayaTilikDiri          string     `gorm:"column:ket_sk_daya_tilik_diri" json:"ket_sk_daya_tilik_diri"`
	KkPembelajaran              string     `gorm:"column:kk_pembelajaran" json:"kk_pembelajaran"`
	KetKkPembelajaran           string     `gorm:"column:ket_kk_pembelajaran" json:"ket_kk_pembelajaran"`
	KetKkPembelajaranLainnya    string     `gorm:"column:ket_kk_pembelajaran_lainnya" json:"ket_kk_pembelajaran_lainnya"`
	KkPenerjamah                string     `gorm:"column:kk_Penerjamah" json:"kk_Penerjamah"`
	KetKkPenerjamahLainnya      string     `gorm:"column:ket_kk_penerjamah_Lainnya" json:"ket_kk_penerjamah_Lainnya"`
	KkBahasaIsyarat             string     `gorm:"column:kk_bahasa_isyarat" json:"kk_bahasa_isyarat"`
	KkKebutuhanEdukasi          string     `gorm:"column:kk_kebutuhan_edukasi" json:"kk_kebutuhan_edukasi"`
	KetKkKebutuhanEdukasi       string     `gorm:"column:ket_kk_kebutuhan_edukasi" json:"ket_kk_kebutuhan_edukasi"`
	Rencana                     string     `gorm:"column:rencana" json:"rencana"`
	Nip                         string     `gorm:"column:nip" json:"nip"`
}

func (PenilaianAwalKeperawatanRalanPsikiatri) TableName() string {
	return "penilaian_awal_keperawatan_ralan_psikiatri"
}
