package rekammedis

import "time"

// PenilaianAwalKeperawatanKebidananRanap tabel `penilaian_awal_keperawatan_kebidanan_ranap` (laporan pemantauan anastesi, RMLaporanPemantauanAnastesi).
type PenilaianAwalKeperawatanKebidananRanap struct {
	NoRawat                                 string     `gorm:"column:no_rawat;primaryKey;autoIncrement:false" json:"no_rawat"`
	Tanggal                                 *time.Time `gorm:"column:tanggal" json:"tanggal"`
	Informasi                               string     `gorm:"column:informasi" json:"informasi"`
	TibaDiruangRawat                        string     `gorm:"column:tiba_diruang_rawat" json:"tiba_diruang_rawat"`
	CaraMasuk                               string     `gorm:"column:cara_masuk" json:"cara_masuk"`
	Keluhan                                 string     `gorm:"column:keluhan" json:"keluhan"`
	Rpk                                     string     `gorm:"column:rpk" json:"rpk"`
	Psk                                     string     `gorm:"column:psk" json:"psk"`
	Rp                                      string     `gorm:"column:rp" json:"rp"`
	Alergi                                  string     `gorm:"column:alergi" json:"alergi"`
	KomplikasiSebelumnya                    string     `gorm:"column:komplikasi_sebelumnya" json:"komplikasi_sebelumnya"`
	KeteranganKomplikasiSebelumnya          string     `gorm:"column:keterangan_komplikasi_sebelumnya" json:"keterangan_komplikasi_sebelumnya"`
	RiwayatMensUmur                         string     `gorm:"column:riwayat_mens_umur" json:"riwayat_mens_umur"`
	RiwayatMensLamanya                      string     `gorm:"column:riwayat_mens_lamanya" json:"riwayat_mens_lamanya"`
	RiwayatMensBanyaknya                    string     `gorm:"column:riwayat_mens_banyaknya" json:"riwayat_mens_banyaknya"`
	RiwayatMensSiklus                       string     `gorm:"column:riwayat_mens_siklus" json:"riwayat_mens_siklus"`
	RiwayatMensKetSiklus                    string     `gorm:"column:riwayat_mens_ket_siklus" json:"riwayat_mens_ket_siklus"`
	RiwayatMensDirasakan                    string     `gorm:"column:riwayat_mens_dirasakan" json:"riwayat_mens_dirasakan"`
	RiwayatPerkawinanStatus                 string     `gorm:"column:riwayat_perkawinan_status" json:"riwayat_perkawinan_status"`
	RiwayatPerkawinanKetStatus              string     `gorm:"column:riwayat_perkawinan_ket_status" json:"riwayat_perkawinan_ket_status"`
	RiwayatPerkawinanUsia1                  string     `gorm:"column:riwayat_perkawinan_usia1" json:"riwayat_perkawinan_usia1"`
	RiwayatPerkawinanKetUsia1               string     `gorm:"column:riwayat_perkawinan_ket_usia1" json:"riwayat_perkawinan_ket_usia1"`
	RiwayatPerkawinanUsia2                  string     `gorm:"column:riwayat_perkawinan_usia2" json:"riwayat_perkawinan_usia2"`
	RiwayatPerkawinanKetUsia2               string     `gorm:"column:riwayat_perkawinan_ket_usia2" json:"riwayat_perkawinan_ket_usia2"`
	RiwayatPerkawinanUsia3                  string     `gorm:"column:riwayat_perkawinan_usia3" json:"riwayat_perkawinan_usia3"`
	RiwayatPerkawinanKetUsia3               string     `gorm:"column:riwayat_perkawinan_ket_usia3" json:"riwayat_perkawinan_ket_usia3"`
	RiwayatPersalinanG                      string     `gorm:"column:riwayat_persalinan_g" json:"riwayat_persalinan_g"`
	RiwayatPersalinanP                      string     `gorm:"column:riwayat_persalinan_p" json:"riwayat_persalinan_p"`
	RiwayatPersalinanA                      string     `gorm:"column:riwayat_persalinan_a" json:"riwayat_persalinan_a"`
	RiwayatPersalinanHidup                  string     `gorm:"column:riwayat_persalinan_hidup" json:"riwayat_persalinan_hidup"`
	RiwayatHamilHpht                        *time.Time `gorm:"column:riwayat_hamil_hpht" json:"riwayat_hamil_hpht"`
	RiwayatHamilUsiahamil                   string     `gorm:"column:riwayat_hamil_usiahamil" json:"riwayat_hamil_usiahamil"`
	RiwayatHamilTp                          *time.Time `gorm:"column:riwayat_hamil_tp" json:"riwayat_hamil_tp"`
	RiwayatHamilImunisasi                   string     `gorm:"column:riwayat_hamil_imunisasi" json:"riwayat_hamil_imunisasi"`
	RiwayatHamilAnc                         string     `gorm:"column:riwayat_hamil_anc" json:"riwayat_hamil_anc"`
	RiwayatHamilAncke                       string     `gorm:"column:riwayat_hamil_ancke" json:"riwayat_hamil_ancke"`
	RiwayatHamilKetAncke                    string     `gorm:"column:riwayat_hamil_ket_ancke" json:"riwayat_hamil_ket_ancke"`
	RiwayatHamilKeluhanHamilMuda            string     `gorm:"column:riwayat_hamil_keluhan_hamil_muda" json:"riwayat_hamil_keluhan_hamil_muda"`
	RiwayatHamilKeluhanHamilTua             string     `gorm:"column:riwayat_hamil_keluhan_hamil_tua" json:"riwayat_hamil_keluhan_hamil_tua"`
	RiwayatKb                               string     `gorm:"column:riwayat_kb" json:"riwayat_kb"`
	RiwayatKbLamanya                        string     `gorm:"column:riwayat_kb_lamanya" json:"riwayat_kb_lamanya"`
	RiwayatKbKomplikasi                     string     `gorm:"column:riwayat_kb_komplikasi" json:"riwayat_kb_komplikasi"`
	RiwayatKbKetKomplikasi                  string     `gorm:"column:riwayat_kb_ket_komplikasi" json:"riwayat_kb_ket_komplikasi"`
	RiwayatKbKapaberhenti                   string     `gorm:"column:riwayat_kb_kapaberhenti" json:"riwayat_kb_kapaberhenti"`
	RiwayatKbAlasanberhenti                 string     `gorm:"column:riwayat_kb_alasanberhenti" json:"riwayat_kb_alasanberhenti"`
	RiwayatGenekologi                       string     `gorm:"column:riwayat_genekologi" json:"riwayat_genekologi"`
	RiwayatKebiasaanObat                    string     `gorm:"column:riwayat_kebiasaan_obat" json:"riwayat_kebiasaan_obat"`
	RiwayatKebiasaanKetObat                 string     `gorm:"column:riwayat_kebiasaan_ket_obat" json:"riwayat_kebiasaan_ket_obat"`
	RiwayatKebiasaanMerokok                 string     `gorm:"column:riwayat_kebiasaan_merokok" json:"riwayat_kebiasaan_merokok"`
	RiwayatKebiasaanKetMerokok              string     `gorm:"column:riwayat_kebiasaan_ket_merokok" json:"riwayat_kebiasaan_ket_merokok"`
	RiwayatKebiasaanAlkohol                 string     `gorm:"column:riwayat_kebiasaan_alkohol" json:"riwayat_kebiasaan_alkohol"`
	RiwayatKebiasaanKetAlkohol              string     `gorm:"column:riwayat_kebiasaan_ket_alkohol" json:"riwayat_kebiasaan_ket_alkohol"`
	RiwayatKebiasaanNarkoba                 string     `gorm:"column:riwayat_kebiasaan_narkoba" json:"riwayat_kebiasaan_narkoba"`
	PemeriksaanKebidananMental              string     `gorm:"column:pemeriksaan_kebidanan_mental" json:"pemeriksaan_kebidanan_mental"`
	PemeriksaanKebidananKeadaanUmum         string     `gorm:"column:pemeriksaan_kebidanan_keadaan_umum" json:"pemeriksaan_kebidanan_keadaan_umum"`
	PemeriksaanKebidananGcs                 string     `gorm:"column:pemeriksaan_kebidanan_gcs" json:"pemeriksaan_kebidanan_gcs"`
	PemeriksaanKebidananTd                  string     `gorm:"column:pemeriksaan_kebidanan_td" json:"pemeriksaan_kebidanan_td"`
	PemeriksaanKebidananNadi                string     `gorm:"column:pemeriksaan_kebidanan_nadi" json:"pemeriksaan_kebidanan_nadi"`
	PemeriksaanKebidananRr                  string     `gorm:"column:pemeriksaan_kebidanan_rr" json:"pemeriksaan_kebidanan_rr"`
	PemeriksaanKebidananSuhu                string     `gorm:"column:pemeriksaan_kebidanan_suhu" json:"pemeriksaan_kebidanan_suhu"`
	PemeriksaanKebidananSpo2                string     `gorm:"column:pemeriksaan_kebidanan_spo2" json:"pemeriksaan_kebidanan_spo2"`
	PemeriksaanKebidananBb                  string     `gorm:"column:pemeriksaan_kebidanan_bb" json:"pemeriksaan_kebidanan_bb"`
	PemeriksaanKebidananTb                  string     `gorm:"column:pemeriksaan_kebidanan_tb" json:"pemeriksaan_kebidanan_tb"`
	PemeriksaanKebidananLila                string     `gorm:"column:pemeriksaan_kebidanan_lila" json:"pemeriksaan_kebidanan_lila"`
	PemeriksaanKebidananTfu                 string     `gorm:"column:pemeriksaan_kebidanan_tfu" json:"pemeriksaan_kebidanan_tfu"`
	PemeriksaanKebidananTbj                 string     `gorm:"column:pemeriksaan_kebidanan_tbj" json:"pemeriksaan_kebidanan_tbj"`
	PemeriksaanKebidananLetak               string     `gorm:"column:pemeriksaan_kebidanan_letak" json:"pemeriksaan_kebidanan_letak"`
	PemeriksaanKebidananPresentasi          string     `gorm:"column:pemeriksaan_kebidanan_presentasi" json:"pemeriksaan_kebidanan_presentasi"`
	PemeriksaanKebidananPenurunan           string     `gorm:"column:pemeriksaan_kebidanan_penurunan" json:"pemeriksaan_kebidanan_penurunan"`
	PemeriksaanKebidananHis                 string     `gorm:"column:pemeriksaan_kebidanan_his" json:"pemeriksaan_kebidanan_his"`
	PemeriksaanKebidananKekuatan            string     `gorm:"column:pemeriksaan_kebidanan_kekuatan" json:"pemeriksaan_kebidanan_kekuatan"`
	PemeriksaanKebidananLamanya             string     `gorm:"column:pemeriksaan_kebidanan_lamanya" json:"pemeriksaan_kebidanan_lamanya"`
	PemeriksaanKebidananDjj                 string     `gorm:"column:pemeriksaan_kebidanan_djj" json:"pemeriksaan_kebidanan_djj"`
	PemeriksaanKebidananKetDjj              string     `gorm:"column:pemeriksaan_kebidanan_ket_djj" json:"pemeriksaan_kebidanan_ket_djj"`
	PemeriksaanKebidananPortio              string     `gorm:"column:pemeriksaan_kebidanan_portio" json:"pemeriksaan_kebidanan_portio"`
	PemeriksaanKebidananPembukaan           string     `gorm:"column:pemeriksaan_kebidanan_pembukaan" json:"pemeriksaan_kebidanan_pembukaan"`
	PemeriksaanKebidananKetuban             string     `gorm:"column:pemeriksaan_kebidanan_ketuban" json:"pemeriksaan_kebidanan_ketuban"`
	PemeriksaanKebidananHodge               string     `gorm:"column:pemeriksaan_kebidanan_hodge" json:"pemeriksaan_kebidanan_hodge"`
	PemeriksaanKebidananPanggul             string     `gorm:"column:pemeriksaan_kebidanan_panggul" json:"pemeriksaan_kebidanan_panggul"`
	PemeriksaanKebidananInspekulo           string     `gorm:"column:pemeriksaan_kebidanan_inspekulo" json:"pemeriksaan_kebidanan_inspekulo"`
	PemeriksaanKebidananKetInspekulo        string     `gorm:"column:pemeriksaan_kebidanan_ket_inspekulo" json:"pemeriksaan_kebidanan_ket_inspekulo"`
	PemeriksaanKebidananLakmus              string     `gorm:"column:pemeriksaan_kebidanan_lakmus" json:"pemeriksaan_kebidanan_lakmus"`
	PemeriksaanKebidananKetLakmus           string     `gorm:"column:pemeriksaan_kebidanan_ket_lakmus" json:"pemeriksaan_kebidanan_ket_lakmus"`
	PemeriksaanKebidananCtg                 string     `gorm:"column:pemeriksaan_kebidanan_ctg" json:"pemeriksaan_kebidanan_ctg"`
	PemeriksaanKebidananKetCtg              string     `gorm:"column:pemeriksaan_kebidanan_ket_ctg" json:"pemeriksaan_kebidanan_ket_ctg"`
	PemeriksaanUmumKepala                   string     `gorm:"column:pemeriksaan_umum_kepala" json:"pemeriksaan_umum_kepala"`
	PemeriksaanUmumMuka                     string     `gorm:"column:pemeriksaan_umum_muka" json:"pemeriksaan_umum_muka"`
	PemeriksaanUmumMata                     string     `gorm:"column:pemeriksaan_umum_mata" json:"pemeriksaan_umum_mata"`
	PemeriksaanUmumHidung                   string     `gorm:"column:pemeriksaan_umum_hidung" json:"pemeriksaan_umum_hidung"`
	PemeriksaanUmumTelinga                  string     `gorm:"column:pemeriksaan_umum_telinga" json:"pemeriksaan_umum_telinga"`
	PemeriksaanUmumMulut                    string     `gorm:"column:pemeriksaan_umum_mulut" json:"pemeriksaan_umum_mulut"`
	PemeriksaanUmumLeher                    string     `gorm:"column:pemeriksaan_umum_leher" json:"pemeriksaan_umum_leher"`
	PemeriksaanUmumDada                     string     `gorm:"column:pemeriksaan_umum_dada" json:"pemeriksaan_umum_dada"`
	PemeriksaanUmumPerut                    string     `gorm:"column:pemeriksaan_umum_perut" json:"pemeriksaan_umum_perut"`
	PemeriksaanUmumGenitalia                string     `gorm:"column:pemeriksaan_umum_genitalia" json:"pemeriksaan_umum_genitalia"`
	PemeriksaanUmumEkstrimitas              string     `gorm:"column:pemeriksaan_umum_ekstrimitas" json:"pemeriksaan_umum_ekstrimitas"`
	PengkajianFungsiKemampuanAktifitas      string     `gorm:"column:pengkajian_fungsi_kemampuan_aktifitas" json:"pengkajian_fungsi_kemampuan_aktifitas"`
	PengkajianFungsiBerjalan                string     `gorm:"column:pengkajian_fungsi_berjalan" json:"pengkajian_fungsi_berjalan"`
	PengkajianFungsiKetBerjalan             string     `gorm:"column:pengkajian_fungsi_ket_berjalan" json:"pengkajian_fungsi_ket_berjalan"`
	PengkajianFungsiAktivitas               string     `gorm:"column:pengkajian_fungsi_aktivitas" json:"pengkajian_fungsi_aktivitas"`
	PengkajianFungsiAmbulasi                string     `gorm:"column:pengkajian_fungsi_ambulasi" json:"pengkajian_fungsi_ambulasi"`
	PengkajianFungsiEkstrimitasAtas         string     `gorm:"column:pengkajian_fungsi_ekstrimitas_atas" json:"pengkajian_fungsi_ekstrimitas_atas"`
	PengkajianFungsiKetEkstrimitasAtas      string     `gorm:"column:pengkajian_fungsi_ket_ekstrimitas_atas" json:"pengkajian_fungsi_ket_ekstrimitas_atas"`
	PengkajianFungsiEkstrimitasBawah        string     `gorm:"column:pengkajian_fungsi_ekstrimitas_bawah" json:"pengkajian_fungsi_ekstrimitas_bawah"`
	PengkajianFungsiKetEkstrimitasBawah     string     `gorm:"column:pengkajian_fungsi_ket_ekstrimitas_bawah" json:"pengkajian_fungsi_ket_ekstrimitas_bawah"`
	PengkajianFungsiKemampuanMenggenggam    string     `gorm:"column:pengkajian_fungsi_kemampuan_menggenggam" json:"pengkajian_fungsi_kemampuan_menggenggam"`
	PengkajianFungsiKetKemampuanMenggenggam string     `gorm:"column:pengkajian_fungsi_ket_kemampuan_menggenggam" json:"pengkajian_fungsi_ket_kemampuan_menggenggam"`
	PengkajianFungsiKoordinasi              string     `gorm:"column:pengkajian_fungsi_koordinasi" json:"pengkajian_fungsi_koordinasi"`
	PengkajianFungsiKetKoordinasi           string     `gorm:"column:pengkajian_fungsi_ket_koordinasi" json:"pengkajian_fungsi_ket_koordinasi"`
	PengkajianFungsiGangguanFungsi          string     `gorm:"column:pengkajian_fungsi_gangguan_fungsi" json:"pengkajian_fungsi_gangguan_fungsi"`
	RiwayatPsikoKondisipsiko                string     `gorm:"column:riwayat_psiko_kondisipsiko" json:"riwayat_psiko_kondisipsiko"`
	RiwayatPsikoAdakahPrilaku               string     `gorm:"column:riwayat_psiko_adakah_prilaku" json:"riwayat_psiko_adakah_prilaku"`
	RiwayatPsikoKetAdakahPrilaku            string     `gorm:"column:riwayat_psiko_ket_adakah_prilaku" json:"riwayat_psiko_ket_adakah_prilaku"`
	RiwayatPsikoGangguanJiwa                string     `gorm:"column:riwayat_psiko_gangguan_jiwa" json:"riwayat_psiko_gangguan_jiwa"`
	RiwayatPsikoHubunganPasien              string     `gorm:"column:riwayat_psiko_hubungan_pasien" json:"riwayat_psiko_hubungan_pasien"`
	RiwayatPsikoTinggalDengan               string     `gorm:"column:riwayat_psiko_tinggal_dengan" json:"riwayat_psiko_tinggal_dengan"`
	RiwayatPsikoKetTinggalDengan            string     `gorm:"column:riwayat_psiko_ket_tinggal_dengan" json:"riwayat_psiko_ket_tinggal_dengan"`
	RiwayatPsikoBudaya                      string     `gorm:"column:riwayat_psiko_budaya" json:"riwayat_psiko_budaya"`
	RiwayatPsikoKetBudaya                   string     `gorm:"column:riwayat_psiko_ket_budaya" json:"riwayat_psiko_ket_budaya"`
	RiwayatPsikoPendPj                      string     `gorm:"column:riwayat_psiko_pend_pj" json:"riwayat_psiko_pend_pj"`
	RiwayatPsikoEdukasiPada                 string     `gorm:"column:riwayat_psiko_edukasi_pada" json:"riwayat_psiko_edukasi_pada"`
	RiwayatPsikoKetEdukasiPada              string     `gorm:"column:riwayat_psiko_ket_edukasi_pada" json:"riwayat_psiko_ket_edukasi_pada"`
	PenilaianNyeri                          string     `gorm:"column:penilaian_nyeri" json:"penilaian_nyeri"`
	PenilaianNyeriPenyebab                  string     `gorm:"column:penilaian_nyeri_penyebab" json:"penilaian_nyeri_penyebab"`
	PenilaianNyeriKetPenyebab               string     `gorm:"column:penilaian_nyeri_ket_penyebab" json:"penilaian_nyeri_ket_penyebab"`
	PenilaianNyeriKualitas                  string     `gorm:"column:penilaian_nyeri_kualitas" json:"penilaian_nyeri_kualitas"`
	PenilaianNyeriKetKualitas               string     `gorm:"column:penilaian_nyeri_ket_kualitas" json:"penilaian_nyeri_ket_kualitas"`
	PenilaianNyeriLokasi                    string     `gorm:"column:penilaian_nyeri_lokasi" json:"penilaian_nyeri_lokasi"`
	PenilaianNyeriMenyebar                  string     `gorm:"column:penilaian_nyeri_menyebar" json:"penilaian_nyeri_menyebar"`
	PenilaianNyeriSkala                     string     `gorm:"column:penilaian_nyeri_skala" json:"penilaian_nyeri_skala"`
	PenilaianNyeriWaktu                     string     `gorm:"column:penilaian_nyeri_waktu" json:"penilaian_nyeri_waktu"`
	PenilaianNyeriHilang                    string     `gorm:"column:penilaian_nyeri_hilang" json:"penilaian_nyeri_hilang"`
	PenilaianNyeriKetHilang                 string     `gorm:"column:penilaian_nyeri_ket_hilang" json:"penilaian_nyeri_ket_hilang"`
	PenilaianNyeriDiberitahukanDokter       string     `gorm:"column:penilaian_nyeri_diberitahukan_dokter" json:"penilaian_nyeri_diberitahukan_dokter"`
	PenilaianNyeriJamDiberitahukanDokter    string     `gorm:"column:penilaian_nyeri_jam_diberitahukan_dokter" json:"penilaian_nyeri_jam_diberitahukan_dokter"`
	PenilaianJatuhSkala1                    string     `gorm:"column:penilaian_jatuh_skala1" json:"penilaian_jatuh_skala1"`
	PenilaianJatuhNilai1                    int        `gorm:"column:penilaian_jatuh_nilai1" json:"penilaian_jatuh_nilai1"`
	PenilaianJatuhSkala2                    string     `gorm:"column:penilaian_jatuh_skala2" json:"penilaian_jatuh_skala2"`
	PenilaianJatuhNilai2                    int        `gorm:"column:penilaian_jatuh_nilai2" json:"penilaian_jatuh_nilai2"`
	PenilaianJatuhSkala3                    string     `gorm:"column:penilaian_jatuh_skala3" json:"penilaian_jatuh_skala3"`
	PenilaianJatuhNilai3                    int        `gorm:"column:penilaian_jatuh_nilai3" json:"penilaian_jatuh_nilai3"`
	PenilaianJatuhSkala4                    string     `gorm:"column:penilaian_jatuh_skala4" json:"penilaian_jatuh_skala4"`
	PenilaianJatuhNilai4                    int        `gorm:"column:penilaian_jatuh_nilai4" json:"penilaian_jatuh_nilai4"`
	PenilaianJatuhSkala5                    string     `gorm:"column:penilaian_jatuh_skala5" json:"penilaian_jatuh_skala5"`
	PenilaianJatuhNilai5                    int        `gorm:"column:penilaian_jatuh_nilai5" json:"penilaian_jatuh_nilai5"`
	PenilaianJatuhSkala6                    string     `gorm:"column:penilaian_jatuh_skala6" json:"penilaian_jatuh_skala6"`
	PenilaianJatuhNilai6                    int        `gorm:"column:penilaian_jatuh_nilai6" json:"penilaian_jatuh_nilai6"`
	PenilaianJatuhTotalnilai                float64    `gorm:"column:penilaian_jatuh_totalnilai" json:"penilaian_jatuh_totalnilai"`
	SkriningGizi1                           string     `gorm:"column:skrining_gizi1" json:"skrining_gizi1"`
	NilaiGizi1                              int        `gorm:"column:nilai_gizi1" json:"nilai_gizi1"`
	SkriningGizi2                           string     `gorm:"column:skrining_gizi2" json:"skrining_gizi2"`
	NilaiGizi2                              int        `gorm:"column:nilai_gizi2" json:"nilai_gizi2"`
	NilaiTotalGizi                          float64    `gorm:"column:nilai_total_gizi" json:"nilai_total_gizi"`
	SkriningGiziDiagnosaKhusus              string     `gorm:"column:skrining_gizi_diagnosa_khusus" json:"skrining_gizi_diagnosa_khusus"`
	SkriningGiziKetDiagnosaKhusus           string     `gorm:"column:skrining_gizi_ket_diagnosa_khusus" json:"skrining_gizi_ket_diagnosa_khusus"`
	SkriningGiziDiketahuiDietisen           string     `gorm:"column:skrining_gizi_diketahui_dietisen" json:"skrining_gizi_diketahui_dietisen"`
	SkriningGiziJamDiketahuiDietisen        string     `gorm:"column:skrining_gizi_jam_diketahui_dietisen" json:"skrining_gizi_jam_diketahui_dietisen"`
	Masalah                                 string     `gorm:"column:masalah" json:"masalah"`
	Rencana                                 string     `gorm:"column:rencana" json:"rencana"`
	Nip1                                    string     `gorm:"column:nip1" json:"nip1"`
	Nip2                                    string     `gorm:"column:nip2" json:"nip2"`
	KdDokter                                string     `gorm:"column:kd_dokter" json:"kd_dokter"`
}

func (PenilaianAwalKeperawatanKebidananRanap) TableName() string {
	return "penilaian_awal_keperawatan_kebidanan_ranap"
}
