package rekammedis

import "time"

// PenilaianAwalKeperawatanRanapBayi tabel `penilaian_awal_keperawatan_ranap_bayi` (penilaian awal keperawatan ranap bayi anak, RMPenilaianAwalKeperawatanRanapBayiAnak).
type PenilaianAwalKeperawatanRanapBayi struct {
	NoRawat                                string     `gorm:"column:no_rawat;primaryKey;autoIncrement:false" json:"no_rawat"`
	Tanggal                                *time.Time `gorm:"column:tanggal" json:"tanggal"`
	Informasi                              string     `gorm:"column:informasi" json:"informasi"`
	KetInformasi                           string     `gorm:"column:ket_informasi" json:"ket_informasi"`
	TibaDiruangRawat                       string     `gorm:"column:tiba_diruang_rawat" json:"tiba_diruang_rawat"`
	Rps                                    string     `gorm:"column:rps" json:"rps"`
	Rpd                                    string     `gorm:"column:rpd" json:"rpd"`
	Rpk                                    string     `gorm:"column:rpk" json:"rpk"`
	Rpo                                    string     `gorm:"column:rpo" json:"rpo"`
	Alergi                                 string     `gorm:"column:alergi" json:"alergi"`
	TumbuhKembangTengkurap                 *string    `gorm:"column:tumbuh_kembang_tengkurap" json:"tumbuh_kembang_tengkurap"`
	TumbuhKembangDuduk                     *string    `gorm:"column:tumbuh_kembang_duduk" json:"tumbuh_kembang_duduk"`
	TumbuhKembangBerdiri                   *string    `gorm:"column:tumbuh_kembang_berdiri" json:"tumbuh_kembang_berdiri"`
	TumbuhKembangGigiPertama               *string    `gorm:"column:tumbuh_kembang_gigi_pertama" json:"tumbuh_kembang_gigi_pertama"`
	TumbuhKembangBerjalan                  *string    `gorm:"column:tumbuh_kembang_berjalan" json:"tumbuh_kembang_berjalan"`
	TumbuhKembangBicara                    *string    `gorm:"column:tumbuh_kembang_bicara" json:"tumbuh_kembang_bicara"`
	TumbuhKembangMembaca                   *string    `gorm:"column:tumbuh_kembang_membaca" json:"tumbuh_kembang_membaca"`
	TumbuhKembangMenulis                   *string    `gorm:"column:tumbuh_kembang_menulis" json:"tumbuh_kembang_menulis"`
	TumbuhKembangGangguanEmosi             *string    `gorm:"column:tumbuh_kembang_gangguan_emosi" json:"tumbuh_kembang_gangguan_emosi"`
	PersalinanAnakke                       string     `gorm:"column:persalinan_anakke" json:"persalinan_anakke"`
	PersalinanDarisaudara                  string     `gorm:"column:persalinan_darisaudara" json:"persalinan_darisaudara"`
	PersalinanKelahiran                    string     `gorm:"column:persalinan_kelahiran" json:"persalinan_kelahiran"`
	PersalinanKelahiranKeterangan          string     `gorm:"column:persalinan_kelahiran_keterangan" json:"persalinan_kelahiran_keterangan"`
	PersalinanUmurKelahiran                string     `gorm:"column:persalinan_umur_kelahiran" json:"persalinan_umur_kelahiran"`
	PersalinanKelainanBawaan               string     `gorm:"column:persalinan_kelainan_bawaan" json:"persalinan_kelainan_bawaan"`
	PersalinanKelainanBawaanKeterangan     string     `gorm:"column:persalinan_kelainan_bawaan_keterangan" json:"persalinan_kelainan_bawaan_keterangan"`
	PersalinanBbLahir                      string     `gorm:"column:persalinan_bb_lahir" json:"persalinan_bb_lahir"`
	PersalinanPbLahir                      string     `gorm:"column:persalinan_pb_lahir" json:"persalinan_pb_lahir"`
	PersalinanLainnya                      string     `gorm:"column:persalinan_lainnya" json:"persalinan_lainnya"`
	FisikKesadaran                         string     `gorm:"column:fisik_kesadaran" json:"fisik_kesadaran"`
	FisikGcs                               string     `gorm:"column:fisik_gcs" json:"fisik_gcs"`
	FisikTd                                string     `gorm:"column:fisik_td" json:"fisik_td"`
	FisikRr                                string     `gorm:"column:fisik_rr" json:"fisik_rr"`
	FisikSuhu                              string     `gorm:"column:fisik_suhu" json:"fisik_suhu"`
	FisikNadi                              string     `gorm:"column:fisik_nadi" json:"fisik_nadi"`
	FisikBb                                string     `gorm:"column:fisik_bb" json:"fisik_bb"`
	FisikTb                                string     `gorm:"column:fisik_tb" json:"fisik_tb"`
	FisikLp                                string     `gorm:"column:fisik_lp" json:"fisik_lp"`
	FisikLk                                string     `gorm:"column:fisik_lk" json:"fisik_lk"`
	FisikLd                                string     `gorm:"column:fisik_ld" json:"fisik_ld"`
	SarafPusatKepala                       string     `gorm:"column:saraf_pusat_kepala" json:"saraf_pusat_kepala"`
	SarafPusatKepalaKeterangan             string     `gorm:"column:saraf_pusat_kepala_keterangan" json:"saraf_pusat_kepala_keterangan"`
	SarafPusatWajah                        string     `gorm:"column:saraf_pusat_wajah" json:"saraf_pusat_wajah"`
	SarafPusatWajahKeterangan              string     `gorm:"column:saraf_pusat_wajah_keterangan" json:"saraf_pusat_wajah_keterangan"`
	SarafPusatLeher                        string     `gorm:"column:saraf_pusat_leher" json:"saraf_pusat_leher"`
	SarafPusatKejang                       string     `gorm:"column:saraf_pusat_kejang" json:"saraf_pusat_kejang"`
	SarafPusatKejangKeterangan             string     `gorm:"column:saraf_pusat_kejang_keterangan" json:"saraf_pusat_kejang_keterangan"`
	SarafPusatSensorik                     string     `gorm:"column:saraf_pusat_sensorik" json:"saraf_pusat_sensorik"`
	KardiovaskulerPulsasi                  string     `gorm:"column:kardiovaskuler_pulsasi" json:"kardiovaskuler_pulsasi"`
	KardiovaskulerSirkulasi                string     `gorm:"column:kardiovaskuler_sirkulasi" json:"kardiovaskuler_sirkulasi"`
	KardiovaskulerSirkulasiKeterangan      string     `gorm:"column:kardiovaskuler_sirkulasi_keterangan" json:"kardiovaskuler_sirkulasi_keterangan"`
	KardiovaskulerDenyutNadi               string     `gorm:"column:kardiovaskuler_denyut_nadi" json:"kardiovaskuler_denyut_nadi"`
	RespirasiRetraksi                      string     `gorm:"column:respirasi_retraksi" json:"respirasi_retraksi"`
	RespirasiPolaNafas                     string     `gorm:"column:respirasi_pola_nafas" json:"respirasi_pola_nafas"`
	RespirasiSuaraNafas                    string     `gorm:"column:respirasi_suara_nafas" json:"respirasi_suara_nafas"`
	RespirasiBatuk                         string     `gorm:"column:respirasi_batuk" json:"respirasi_batuk"`
	RespirasiVolume                        string     `gorm:"column:respirasi_volume" json:"respirasi_volume"`
	RespirasiJenisPernapasan               string     `gorm:"column:respirasi_jenis_pernapasan" json:"respirasi_jenis_pernapasan"`
	RespirasiJenisPernapasanKeterangan     string     `gorm:"column:respirasi_jenis_pernapasan_keterangan" json:"respirasi_jenis_pernapasan_keterangan"`
	RespirasiIrama                         string     `gorm:"column:respirasi_irama" json:"respirasi_irama"`
	GastroMulut                            string     `gorm:"column:gastro_mulut" json:"gastro_mulut"`
	GastroMulutKeterangan                  string     `gorm:"column:gastro_mulut_keterangan" json:"gastro_mulut_keterangan"`
	GastroTenggorakan                      string     `gorm:"column:gastro_tenggorakan" json:"gastro_tenggorakan"`
	GastroTenggorakanKeterangan            string     `gorm:"column:gastro_tenggorakan_keterangan" json:"gastro_tenggorakan_keterangan"`
	GastroLidah                            string     `gorm:"column:gastro_lidah" json:"gastro_lidah"`
	GastroLidahKeterangan                  string     `gorm:"column:gastro_lidah_keterangan" json:"gastro_lidah_keterangan"`
	GastroAbdomen                          string     `gorm:"column:gastro_abdomen" json:"gastro_abdomen"`
	GastroAbdomenKeterangan                string     `gorm:"column:gastro_abdomen_keterangan" json:"gastro_abdomen_keterangan"`
	GastroGigi                             string     `gorm:"column:gastro_gigi" json:"gastro_gigi"`
	GastroGigiKeterangan                   string     `gorm:"column:gastro_gigi_keterangan" json:"gastro_gigi_keterangan"`
	GastroUsus                             string     `gorm:"column:gastro_usus" json:"gastro_usus"`
	GastroAnus                             string     `gorm:"column:gastro_anus" json:"gastro_anus"`
	NeurologiSensorik                      string     `gorm:"column:neurologi_sensorik" json:"neurologi_sensorik"`
	NeurologiPengilihatan                  string     `gorm:"column:neurologi_pengilihatan" json:"neurologi_pengilihatan"`
	NeurologiPengilihatanKeterangan        string     `gorm:"column:neurologi_pengilihatan_keterangan" json:"neurologi_pengilihatan_keterangan"`
	NeurologiAlatBantuPenglihatan          string     `gorm:"column:neurologi_alat_bantu_penglihatan" json:"neurologi_alat_bantu_penglihatan"`
	NeurologiMotorik                       string     `gorm:"column:neurologi_motorik" json:"neurologi_motorik"`
	NeurologiPendengaran                   string     `gorm:"column:neurologi_pendengaran" json:"neurologi_pendengaran"`
	NeurologiBicara                        string     `gorm:"column:neurologi_bicara" json:"neurologi_bicara"`
	NeurologiBicaraKeterangan              string     `gorm:"column:neurologi_bicara_keterangan" json:"neurologi_bicara_keterangan"`
	NeurologiOtot                          string     `gorm:"column:neurologi_otot" json:"neurologi_otot"`
	InteKulit                              string     `gorm:"column:inte_kulit" json:"inte_kulit"`
	InteWarnaKulit                         string     `gorm:"column:inte_warna_kulit" json:"inte_warna_kulit"`
	InteTugor                              string     `gorm:"column:inte_tugor" json:"inte_tugor"`
	InteDecubi                             string     `gorm:"column:inte_decubi" json:"inte_decubi"`
	MuskuOdema                             string     `gorm:"column:musku_odema" json:"musku_odema"`
	MuskuOdemaKeterangan                   string     `gorm:"column:musku_odema_keterangan" json:"musku_odema_keterangan"`
	MuskuPegerakansendi                    string     `gorm:"column:musku_pegerakansendi" json:"musku_pegerakansendi"`
	MuskuOtot                              string     `gorm:"column:musku_otot" json:"musku_otot"`
	MuskuFraktur                           string     `gorm:"column:musku_fraktur" json:"musku_fraktur"`
	MuskuFrakturKeterangan                 string     `gorm:"column:musku_fraktur_keterangan" json:"musku_fraktur_keterangan"`
	MuskuNyerisendi                        string     `gorm:"column:musku_nyerisendi" json:"musku_nyerisendi"`
	MuskuNyerisendiKeterangan              string     `gorm:"column:musku_nyerisendi_keterangan" json:"musku_nyerisendi_keterangan"`
	EliminasiBabFrekuensi                  string     `gorm:"column:eliminasi_bab_frekuensi" json:"eliminasi_bab_frekuensi"`
	EliminasiBabFrekuensiPer               string     `gorm:"column:eliminasi_bab_frekuensi_per" json:"eliminasi_bab_frekuensi_per"`
	EliminasiBabKonsistesi                 string     `gorm:"column:eliminasi_bab_konsistesi" json:"eliminasi_bab_konsistesi"`
	EliminasiBabWarna                      string     `gorm:"column:eliminasi_bab_warna" json:"eliminasi_bab_warna"`
	EliminasiBakFrekuensi                  string     `gorm:"column:eliminasi_bak_frekuensi" json:"eliminasi_bak_frekuensi"`
	EliminasiBakFrekuensiPer               string     `gorm:"column:eliminasi_bak_frekuensi_per" json:"eliminasi_bak_frekuensi_per"`
	EliminasiBakWarna                      string     `gorm:"column:eliminasi_bak_warna" json:"eliminasi_bak_warna"`
	EliminasiBakLainlain                   string     `gorm:"column:eliminasi_bak_lainlain" json:"eliminasi_bak_lainlain"`
	PsikoKondisi                           string     `gorm:"column:psiko_kondisi" json:"psiko_kondisi"`
	PsikoPerilaku                          string     `gorm:"column:psiko_perilaku" json:"psiko_perilaku"`
	PsikoPerilakuKeterangan                string     `gorm:"column:psiko_perilaku_keterangan" json:"psiko_perilaku_keterangan"`
	PsikoGangguanJiwa                      string     `gorm:"column:psiko_gangguan_jiwa" json:"psiko_gangguan_jiwa"`
	PsikoHubunganPasien                    string     `gorm:"column:psiko_hubungan_pasien" json:"psiko_hubungan_pasien"`
	PsikoTinggalDengan                     string     `gorm:"column:psiko_tinggal_dengan" json:"psiko_tinggal_dengan"`
	PsikoTinggalDenganKeterangan           string     `gorm:"column:psiko_tinggal_dengan_keterangan" json:"psiko_tinggal_dengan_keterangan"`
	PsikoPekerjaanPj                       string     `gorm:"column:psiko_pekerjaan_pj" json:"psiko_pekerjaan_pj"`
	PsikoNilaiKepercayaan                  string     `gorm:"column:psiko_nilai_kepercayaan" json:"psiko_nilai_kepercayaan"`
	PsikoNilaiKepercayaanKeterangan        string     `gorm:"column:psiko_nilai_kepercayaan_keterangan" json:"psiko_nilai_kepercayaan_keterangan"`
	PsikoPendidikanPj                      string     `gorm:"column:psiko_pendidikan_pj" json:"psiko_pendidikan_pj"`
	PsikoEdukasi                           string     `gorm:"column:psiko_edukasi" json:"psiko_edukasi"`
	PsikoEdukasiKeterangan                 string     `gorm:"column:psiko_edukasi_keterangan" json:"psiko_edukasi_keterangan"`
	EdukasiBahasa                          string     `gorm:"column:edukasi_bahasa" json:"edukasi_bahasa"`
	EdukasiBacaTulis                       string     `gorm:"column:edukasi_baca_tulis" json:"edukasi_baca_tulis"`
	EdukasiPenerjemah                      string     `gorm:"column:edukasi_penerjemah" json:"edukasi_penerjemah"`
	EdukasiPenerjemahKeterangan            string     `gorm:"column:edukasi_penerjemah_keterangan" json:"edukasi_penerjemah_keterangan"`
	EdukasiTerdapatHambatan                string     `gorm:"column:edukasi_terdapat_hambatan" json:"edukasi_terdapat_hambatan"`
	EdukasiHambatanBelajar                 string     `gorm:"column:edukasi_hambatan_belajar" json:"edukasi_hambatan_belajar"`
	EdukasiHambatanBelajarKeterangan       string     `gorm:"column:edukasi_hambatan_belajar_keterangan" json:"edukasi_hambatan_belajar_keterangan"`
	EdukasiHambatanBicara                  string     `gorm:"column:edukasi_hambatan_bicara" json:"edukasi_hambatan_bicara"`
	EdukasiBahasaIsyarat                   string     `gorm:"column:edukasi_bahasa_isyarat" json:"edukasi_bahasa_isyarat"`
	EdukasiCaraBelajar                     string     `gorm:"column:edukasi_cara_belajar" json:"edukasi_cara_belajar"`
	EdukasiMenerimaInformasi               string     `gorm:"column:edukasi_menerima_informasi" json:"edukasi_menerima_informasi"`
	EdukasiMenerimaInformasiKeterangan     string     `gorm:"column:edukasi_menerima_informasi_keterangan" json:"edukasi_menerima_informasi_keterangan"`
	EdukasiNutrisi                         string     `gorm:"column:edukasi_nutrisi" json:"edukasi_nutrisi"`
	EdukasiPenyakit                        string     `gorm:"column:edukasi_penyakit" json:"edukasi_penyakit"`
	EdukasiPengobatan                      string     `gorm:"column:edukasi_pengobatan" json:"edukasi_pengobatan"`
	EdukasiPerawatan                       string     `gorm:"column:edukasi_perawatan" json:"edukasi_perawatan"`
	SkriningGizi1                          string     `gorm:"column:skrining_gizi1" json:"skrining_gizi1"`
	NilaiGizi1                             string     `gorm:"column:nilai_gizi1" json:"nilai_gizi1"`
	SkriningGizi2                          string     `gorm:"column:skrining_gizi2" json:"skrining_gizi2"`
	NilaiGizi2                             string     `gorm:"column:nilai_gizi2" json:"nilai_gizi2"`
	SkriningGizi3                          string     `gorm:"column:skrining_gizi3" json:"skrining_gizi3"`
	NilaiGizi3                             string     `gorm:"column:nilai_gizi3" json:"nilai_gizi3"`
	SkriningGizi4                          string     `gorm:"column:skrining_gizi4" json:"skrining_gizi4"`
	NilaiGizi4                             string     `gorm:"column:nilai_gizi4" json:"nilai_gizi4"`
	TotalNilai                             string     `gorm:"column:total_nilai" json:"total_nilai"`
	KeteranganSkriningGizi                 string     `gorm:"column:keterangan_skrining_gizi" json:"keterangan_skrining_gizi"`
	PenilaianHumptydumptySkala1            *string    `gorm:"column:penilaian_humptydumpty_skala1" json:"penilaian_humptydumpty_skala1"`
	PenilaianHumptydumptyNilai1            *int       `gorm:"column:penilaian_humptydumpty_nilai1" json:"penilaian_humptydumpty_nilai1"`
	PenilaianHumptydumptySkala2            *string    `gorm:"column:penilaian_humptydumpty_skala2" json:"penilaian_humptydumpty_skala2"`
	PenilaianHumptydumptyNilai2            *int       `gorm:"column:penilaian_humptydumpty_nilai2" json:"penilaian_humptydumpty_nilai2"`
	PenilaianHumptydumptySkala3            *string    `gorm:"column:penilaian_humptydumpty_skala3" json:"penilaian_humptydumpty_skala3"`
	PenilaianHumptydumptyNilai3            *int       `gorm:"column:penilaian_humptydumpty_nilai3" json:"penilaian_humptydumpty_nilai3"`
	PenilaianHumptydumptySkala4            *string    `gorm:"column:penilaian_humptydumpty_skala4" json:"penilaian_humptydumpty_skala4"`
	PenilaianHumptydumptyNilai4            *int       `gorm:"column:penilaian_humptydumpty_nilai4" json:"penilaian_humptydumpty_nilai4"`
	PenilaianHumptydumptySkala5            *string    `gorm:"column:penilaian_humptydumpty_skala5" json:"penilaian_humptydumpty_skala5"`
	PenilaianHumptydumptyNilai5            *int       `gorm:"column:penilaian_humptydumpty_nilai5" json:"penilaian_humptydumpty_nilai5"`
	PenilaianHumptydumptySkala6            *string    `gorm:"column:penilaian_humptydumpty_skala6" json:"penilaian_humptydumpty_skala6"`
	PenilaianHumptydumptyNilai6            *int       `gorm:"column:penilaian_humptydumpty_nilai6" json:"penilaian_humptydumpty_nilai6"`
	PenilaianHumptydumptySkala7            *string    `gorm:"column:penilaian_humptydumpty_skala7" json:"penilaian_humptydumpty_skala7"`
	PenilaianHumptydumptyNilai7            *int       `gorm:"column:penilaian_humptydumpty_nilai7" json:"penilaian_humptydumpty_nilai7"`
	PenilaianHumptydumptyTotalnilai        *int       `gorm:"column:penilaian_humptydumpty_totalnilai" json:"penilaian_humptydumpty_totalnilai"`
	HasilSkriningPenilaianHumptydumpty     *string    `gorm:"column:hasil_skrining_penilaian_humptydumpty" json:"hasil_skrining_penilaian_humptydumpty"`
	NyeriWajah                             string     `gorm:"column:nyeri_wajah" json:"nyeri_wajah"`
	NyeriNilaiWajah                        string     `gorm:"column:nyeri_nilai_wajah" json:"nyeri_nilai_wajah"`
	NyeriKaki                              string     `gorm:"column:nyeri_kaki" json:"nyeri_kaki"`
	NyeriNilaiKaki                         string     `gorm:"column:nyeri_nilai_kaki" json:"nyeri_nilai_kaki"`
	NyeriAktifitas                         string     `gorm:"column:nyeri_aktifitas" json:"nyeri_aktifitas"`
	NyeriNilaiAktifitas                    string     `gorm:"column:nyeri_nilai_aktifitas" json:"nyeri_nilai_aktifitas"`
	NyeriMenangis                          string     `gorm:"column:nyeri_menangis" json:"nyeri_menangis"`
	NyeriNilaiMenangis                     string     `gorm:"column:nyeri_nilai_menangis" json:"nyeri_nilai_menangis"`
	NyeriBersuara                          string     `gorm:"column:nyeri_bersuara" json:"nyeri_bersuara"`
	NyeriNilaiBersuara                     string     `gorm:"column:nyeri_nilai_bersuara" json:"nyeri_nilai_bersuara"`
	NyeriNilaiTotal                        string     `gorm:"column:nyeri_nilai_total" json:"nyeri_nilai_total"`
	NyeriKondisi                           string     `gorm:"column:nyeri_kondisi" json:"nyeri_kondisi"`
	NyeriLokasi                            string     `gorm:"column:nyeri_lokasi" json:"nyeri_lokasi"`
	NyeriDurasi                            string     `gorm:"column:nyeri_durasi" json:"nyeri_durasi"`
	NyeriFrekuensi                         string     `gorm:"column:nyeri_frekuensi" json:"nyeri_frekuensi"`
	NyeriHilang                            string     `gorm:"column:nyeri_hilang" json:"nyeri_hilang"`
	NyeriHilangKeterangan                  string     `gorm:"column:nyeri_hilang_keterangan" json:"nyeri_hilang_keterangan"`
	NyeriDiberitahukanPadaDokter           string     `gorm:"column:nyeri_diberitahukan_pada_dokter" json:"nyeri_diberitahukan_pada_dokter"`
	NyeriDiberitahukanPadaDokterKeterangan string     `gorm:"column:nyeri_diberitahukan_pada_dokter_keterangan" json:"nyeri_diberitahukan_pada_dokter_keterangan"`
	InformasiPerencanaanPulang             string     `gorm:"column:informasi_perencanaan_pulang" json:"informasi_perencanaan_pulang"`
	LamaRatarata                           string     `gorm:"column:lama_ratarata" json:"lama_ratarata"`
	PerencanaanPulang                      *time.Time `gorm:"column:perencanaan_pulang" json:"perencanaan_pulang"`
	KondisiKlinisPulang                    string     `gorm:"column:kondisi_klinis_pulang" json:"kondisi_klinis_pulang"`
	PerawatanLanjutanDirumah               string     `gorm:"column:perawatan_lanjutan_dirumah" json:"perawatan_lanjutan_dirumah"`
	CaraTransportasiPulang                 string     `gorm:"column:cara_transportasi_pulang" json:"cara_transportasi_pulang"`
	TransportasiDigunakan                  string     `gorm:"column:transportasi_digunakan" json:"transportasi_digunakan"`
	Rencana                                *string    `gorm:"column:rencana" json:"rencana"`
	Nip1                                   string     `gorm:"column:nip1" json:"nip1"`
	Nip2                                   string     `gorm:"column:nip2" json:"nip2"`
	KdDokter                               string     `gorm:"column:kd_dokter" json:"kd_dokter"`
}

func (PenilaianAwalKeperawatanRanapBayi) TableName() string {
	return "penilaian_awal_keperawatan_ranap_bayi"
}
