// Kode dibangkitkan dari sik.sql + source/src/rekammedis.
package rekammedis

// FormInfo identitas form asesmen untuk ringkasan riwayat.
type FormInfo struct {
	Slug  string `json:"slug"`
	Label string `json:"label"`
	Table string `json:"-"`
}

// DaftarForm seluruh form asesmen rekam medis.
var DaftarForm = []FormInfo{
	{Slug: "admisi-skoring-tolac", Label: "admisi skoring TOLAC", Table: "admisi_skoring_tolac"},
	{Slug: "catatan-adime-gizi", Label: "catatan ADIME gizi", Table: "catatan_adime_gizi"},
	{Slug: "catatan-anestesi-sedasi", Label: "catatan anastesi sedasi", Table: "catatan_anestesi_sedasi"},
	{Slug: "catatan-pengkajian-paska-operasi", Label: "catatan pengkajian paska operasi", Table: "catatan_pengkajian_paska_operasi"},
	{Slug: "catatan-persalinan", Label: "catatan persalinan", Table: "catatan_persalinan"},
	{Slug: "checklist-kesiapan-anestesi", Label: "checklist kesiapan anestesi", Table: "checklist_kesiapan_anestesi"},
	{Slug: "checklist-kriteria-keluar-hcu", Label: "checklist kriteria keluar HCU", Table: "checklist_kriteria_keluar_hcu"},
	{Slug: "checklist-kriteria-keluar-icu", Label: "checklist kriteria keluar ICU", Table: "checklist_kriteria_keluar_icu"},
	{Slug: "checklist-kriteria-keluar-isolasi", Label: "checklist kriteria keluar isolasi", Table: "checklist_kriteria_keluar_isolasi"},
	{Slug: "checklist-kriteria-keluar-nicu", Label: "checklist kriteria keluar NICU", Table: "checklist_kriteria_keluar_nicu"},
	{Slug: "checklist-kriteria-keluar-picu", Label: "checklist kriteria keluar PICU", Table: "checklist_kriteria_keluar_picu"},
	{Slug: "checklist-kriteria-masuk-hcu", Label: "checklist kriteria masuk HCU", Table: "checklist_kriteria_masuk_hcu"},
	{Slug: "checklist-kriteria-masuk-icu", Label: "checklist kriteria masuk ICU", Table: "checklist_kriteria_masuk_icu"},
	{Slug: "checklist-kriteria-masuk-isolasi", Label: "checklist kriteria masuk isolasi", Table: "checklist_kriteria_masuk_isolasi"},
	{Slug: "checklist-kriteria-masuk-nicu", Label: "checklist kriteria masuk NICU", Table: "checklist_kriteria_masuk_nicu"},
	{Slug: "checklist-kriteria-masuk-picu", Label: "checklist kriteria masuk PICU", Table: "checklist_kriteria_masuk_picu"},
	{Slug: "checklist-pemberian-fibrinolitik", Label: "checklist pemberian fibrinolitik", Table: "checklist_pemberian_fibrinolitik"},
	{Slug: "checklist-post-operasi", Label: "checklist post operasi", Table: "checklist_post_operasi"},
	{Slug: "checklist-pre-operasi", Label: "checklist pre operasi", Table: "checklist_pre_operasi"},
	{Slug: "asuhan-gizi", Label: "asuhan gizi", Table: "asuhan_gizi"},
	{Slug: "catatan-cairan-hemodialisa", Label: "catatan cairan hemodialisa", Table: "catatan_cairan_hemodialisa"},
	{Slug: "catatan-cek-gds", Label: "catatan cek GDS", Table: "catatan_cek_gds"},
	{Slug: "catatan-keperawatan-ralan", Label: "catatan keperawatan ralan", Table: "catatan_keperawatan_ralan"},
	{Slug: "catatan-keperawatan-ranap", Label: "catatan keperawatan ranap", Table: "catatan_keperawatan_ranap"},
	{Slug: "catatan-keseimbangan-cairan", Label: "catatan keseimbangan cairan", Table: "catatan_keseimbangan_cairan"},
	{Slug: "catatan-observasi-bayi", Label: "catatan observasi bayi", Table: "catatan_observasi_bayi"},
	{Slug: "catatan-observasi-chbp", Label: "catatan observasi CHBP", Table: "catatan_observasi_chbp"},
	{Slug: "catatan-observasi-hemodialisa", Label: "catatan observasi hemodialisa", Table: "catatan_observasi_hemodialisa"},
	{Slug: "catatan-observasi-igd", Label: "catatan observasi IGD", Table: "catatan_observasi_igd"},
	{Slug: "catatan-observasi-induksi-persalinan", Label: "catatan observasi induksi persalinan", Table: "catatan_observasi_induksi_persalinan"},
	{Slug: "catatan-observasi-ranap", Label: "catatan observasi ranap", Table: "catatan_observasi_ranap"},
	{Slug: "catatan-observasi-ranap-kebidanan", Label: "catatan observasi ranap kebidanan", Table: "catatan_observasi_ranap_kebidanan"},
	{Slug: "catatan-observasi-ranap-postpartum", Label: "catatan observasi ranap post partum", Table: "catatan_observasi_ranap_postpartum"},
	{Slug: "catatan-observasi-restrain-nonfarma", Label: "catatan observasi restrain non farmakologi", Table: "catatan_observasi_restrain_nonfarma"},
	{Slug: "catatan-observasi-ruang-ok", Label: "catatan observasi ruang operasi", Table: "catatan_observasi_ruang_ok"},
	{Slug: "catatan-observasi-ventilator", Label: "catatan observasi ventilator", Table: "catatan_observasi_ventilator"},
	{Slug: "follow-up-dbd", Label: "follow up DBD", Table: "follow_up_dbd"},
	{Slug: "intervensi-nyeri-farmakologi", Label: "intervensi nyeri farmakologi", Table: "intervensi_nyeri_farmakologi"},
	{Slug: "intervensi-nyeri-nonfarmakologi", Label: "intervensi nyeri non farmakologi", Table: "intervensi_nyeri_nonfarmakologi"},
	{Slug: "monitoring-asuhan-gizi", Label: "monitoring asuhan gizi", Table: "monitoring_asuhan_gizi"},
	{Slug: "monitoring-reaksi-tranfusi", Label: "monitoring reaksi tranfusi", Table: "monitoring_reaksi_tranfusi"},
	{Slug: "resume-pasien", Label: "resume pasien", Table: "resume_pasien"},
	{Slug: "resume-pasien-ranap", Label: "resume pasien ranap", Table: "resume_pasien_ranap"},
	{Slug: "skrining-gizi-kehamilan", Label: "skrining gizi kehamilan", Table: "skrining_gizi_kehamilan"},
	{Slug: "skrining-gizi", Label: "skrining gizi lanjut", Table: "skrining_gizi"},
	{Slug: "deteksi-dini-corona", Label: "deteksi dini corona", Table: "deteksi_dini_corona"},
	{Slug: "edukasi-pasien-keluarga-rj", Label: "edukasi pasien keluarga rawat jalan", Table: "edukasi_pasien_keluarga_rj"},
	{Slug: "hasil-endoskopi-faring-laring", Label: "hasil endoskopi faring laring", Table: "hasil_endoskopi_faring_laring"},
	{Slug: "hasil-endoskopi-hidung", Label: "hasil endoskopi hidung", Table: "hasil_endoskopi_hidung"},
	{Slug: "hasil-endoskopi-telinga", Label: "hasil endoskopi telinga", Table: "hasil_endoskopi_telinga"},
	{Slug: "hasil-pemeriksaan-ekg", Label: "hasil pemeriksaan EKG", Table: "hasil_pemeriksaan_ekg"},
	{Slug: "hasil-pemeriksaan-echo", Label: "hasil pemeriksaan echo", Table: "hasil_pemeriksaan_echo"},
	{Slug: "hasil-pemeriksaan-echo-pediatrik", Label: "hasil pemeriksaan echo pediatrik", Table: "hasil_pemeriksaan_echo_pediatrik"},
	{Slug: "hasil-pemeriksaan-oct", Label: "hasil pemeriksaan OCT", Table: "hasil_pemeriksaan_oct"},
	{Slug: "hasil-pemeriksaan-slit-lamp", Label: "hasil pemeriksaan slit lamp", Table: "hasil_pemeriksaan_slit_lamp"},
	{Slug: "hasil-pemeriksaan-treadmill", Label: "hasil pemeriksaan treadmill", Table: "hasil_pemeriksaan_treadmill"},
	{Slug: "hasil-pemeriksaan-usg", Label: "hasil pemeriksaan USG", Table: "hasil_pemeriksaan_usg"},
	{Slug: "hasil-pemeriksaan-usg-abdomen", Label: "hasil pemeriksaan USG abdomen", Table: "hasil_pemeriksaan_usg_abdomen"},
	{Slug: "hasil-pemeriksaan-usg-gynecologi", Label: "hasil pemeriksaan USG gynecologi", Table: "hasil_pemeriksaan_usg_gynecologi"},
	{Slug: "hasil-pemeriksaan-usg-neonatus", Label: "hasil pemeriksaan USG neonatus", Table: "hasil_pemeriksaan_usg_neonatus"},
	{Slug: "hasil-pemeriksaan-usg-urologi", Label: "hasil pemeriksaan USG urologi", Table: "hasil_pemeriksaan_usg_urologi"},
	{Slug: "hasil-tindakan-eswl", Label: "hasil tindakan ESWL", Table: "hasil_tindakan_eswl"},
	{Slug: "hemodialisa", Label: "hemodialisa", Table: "hemodialisa"},
	{Slug: "konseling-farmasi", Label: "konseling farmasi", Table: "konseling_farmasi"},
	{Slug: "penilaian-awal-keperawatan-kebidanan-ranap", Label: "laporan pemantauan anastesi", Table: "penilaian_awal_keperawatan_kebidanan_ranap"},
	{Slug: "laporan-tindakan", Label: "laporan tindakan", Table: "laporan_tindakan"},
	{Slug: "layanan-kedokteran-fisik-rehabilitasi", Label: "layanan kedokteran fisik rehabilitasi", Table: "layanan_kedokteran_fisik_rehabilitasi"},
	{Slug: "layanan-program-kfr", Label: "layanan program KFR", Table: "layanan_program_kfr"},
	{Slug: "penilaian-mcu", Label: "MCU", Table: "penilaian_mcu"},
	{Slug: "skor-aldrette-pasca-anestesi", Label: "monitoring aldrette pasca anestesi", Table: "skor_aldrette_pasca_anestesi"},
	{Slug: "skor-bromage-pasca-anestesi", Label: "monitoring bromage pasca anestesi", Table: "skor_bromage_pasca_anestesi"},
	{Slug: "skor-steward-pasca-anestesi", Label: "monitoring steward pasca anestesi", Table: "skor_steward_pasca_anestesi"},
	{Slug: "pelaksanaan-informasi-edukasi", Label: "pelaksanaan informasi edukasi", Table: "pelaksanaan_informasi_edukasi"},
	{Slug: "monitoring-efek-samping-obat", Label: "pelaporan efek samping obat", Table: "monitoring_efek_samping_obat"},
	{Slug: "pemantauan-pews-dewasa", Label: "pemantauan EWSD", Table: "pemantauan_pews_dewasa"},
	{Slug: "pemantauan-ews-neonatus", Label: "pemantauan EWS neonatus", Table: "pemantauan_ews_neonatus"},
	{Slug: "pemantauan-meows-obstetri", Label: "pemantauan MEOWS", Table: "pemantauan_meows_obstetri"},
	{Slug: "pemantauan-pews-anak", Label: "pemantauan PEWS", Table: "pemantauan_pews_anak"},
	{Slug: "penatalaksanaan-terapi-okupasi", Label: "penatalaksanaan terapi okupasi", Table: "penatalaksanaan_terapi_okupasi"},
	{Slug: "pengkajian-restrain", Label: "pengkajian restrain", Table: "pengkajian_restrain"},
	{Slug: "penilaian-awal-keperawatan-ralan-bayi", Label: "penilaian awal keperawatan bayi anak", Table: "penilaian_awal_keperawatan_ralan_bayi"},
	{Slug: "penilaian-awal-keperawatan-gigi", Label: "penilaian awal keperawatan gigi", Table: "penilaian_awal_keperawatan_gigi"},
	{Slug: "penilaian-awal-keperawatan-igd", Label: "penilaian awal keperawatan IGD", Table: "penilaian_awal_keperawatan_igd"},
	{Slug: "penilaian-awal-keperawatan-kebidanan", Label: "penilaian awal keperawatan kebidanan", Table: "penilaian_awal_keperawatan_kebidanan"},
	{Slug: "penilaian-awal-keperawatan-mata", Label: "penilaian awal keperawatan mata", Table: "penilaian_awal_keperawatan_mata"},
	{Slug: "penilaian-awal-keperawatan-ralan", Label: "penilaian awal keperawatan ralan", Table: "penilaian_awal_keperawatan_ralan"},
	{Slug: "penilaian-awal-keperawatan-ralan-geriatri", Label: "penilaian awal keperawatan ralan geriatri", Table: "penilaian_awal_keperawatan_ralan_geriatri"},
	{Slug: "penilaian-awal-keperawatan-ralan-psikiatri", Label: "penilaian awal keperawatan ralan psikiatri", Table: "penilaian_awal_keperawatan_ralan_psikiatri"},
	{Slug: "penilaian-awal-keperawatan-ranap", Label: "penilaian awal keperawatan ranap", Table: "penilaian_awal_keperawatan_ranap"},
	{Slug: "penilaian-awal-keperawatan-ranap-bayi", Label: "penilaian awal keperawatan ranap bayi anak", Table: "penilaian_awal_keperawatan_ranap_bayi"},
	{Slug: "penilaian-awal-keperawatan-ranap-neonatus", Label: "penilaian awal keperawatan ranap neonatus", Table: "penilaian_awal_keperawatan_ranap_neonatus"},
	{Slug: "penilaian-medis-hemodialisa", Label: "penilaian awal medis hemodialisa", Table: "penilaian_medis_hemodialisa"},
	{Slug: "penilaian-medis-igd", Label: "penilaian awal medis IGD", Table: "penilaian_medis_igd"},
	{Slug: "penilaian-medis-ralan-gawat-darurat-psikiatri", Label: "penilaian awal medis IGD psikiatri", Table: "penilaian_medis_ralan_gawat_darurat_psikiatri"},
	{Slug: "penilaian-medis-ralan-anak", Label: "penilaian awal medis ralan anak", Table: "penilaian_medis_ralan_anak"},
	{Slug: "penilaian-medis-ralan-bedah", Label: "penilaian awal medis ralan bedah", Table: "penilaian_medis_ralan_bedah"},
	{Slug: "penilaian-medis-ralan-bedah-mulut", Label: "penilaian awal medis ralan bedah mulut", Table: "penilaian_medis_ralan_bedah_mulut"},
	{Slug: "penilaian-medis-ralan", Label: "penilaian awal medis ralan dewasa", Table: "penilaian_medis_ralan"},
	{Slug: "penilaian-medis-ralan-geriatri", Label: "penilaian awal medis ralan geriatri", Table: "penilaian_medis_ralan_geriatri"},
	{Slug: "penilaian-medis-ralan-jantung", Label: "penilaian awal medis ralan jantung", Table: "penilaian_medis_ralan_jantung"},
	{Slug: "penilaian-medis-ralan-kandungan", Label: "penilaian awal medis ralan kandungan", Table: "penilaian_medis_ralan_kandungan"},
	{Slug: "penilaian-medis-ralan-kulitdankelamin", Label: "penilaian awal medis ralan kulit dan kelamin", Table: "penilaian_medis_ralan_kulitdankelamin"},
	{Slug: "penilaian-medis-ralan-mata", Label: "penilaian awal medis ralan mata", Table: "penilaian_medis_ralan_mata"},
	{Slug: "penilaian-medis-ralan-neurologi", Label: "penilaian awal medis ralan neurologi", Table: "penilaian_medis_ralan_neurologi"},
	{Slug: "penilaian-medis-ralan-orthopedi", Label: "penilaian awal medis ralan orthopedi", Table: "penilaian_medis_ralan_orthopedi"},
	{Slug: "penilaian-medis-ralan-paru", Label: "penilaian awal medis ralan paru", Table: "penilaian_medis_ralan_paru"},
	{Slug: "penilaian-medis-ralan-penyakit-dalam", Label: "penilaian awal medis ralan penyakit dalam", Table: "penilaian_medis_ralan_penyakit_dalam"},
	{Slug: "penilaian-medis-ralan-psikiatrik", Label: "penilaian awal medis ralan psikiatrik", Table: "penilaian_medis_ralan_psikiatrik"},
	{Slug: "penilaian-medis-ralan-rehab-medik", Label: "penilaian awal medis ralan rehab medik", Table: "penilaian_medis_ralan_rehab_medik"},
	{Slug: "penilaian-medis-ralan-tht", Label: "penilaian awal medis ralan THT", Table: "penilaian_medis_ralan_tht"},
	{Slug: "penilaian-medis-ralan-urologi", Label: "penilaian awal medis ralan urologi", Table: "penilaian_medis_ralan_urologi"},
	{Slug: "penilaian-medis-ranap", Label: "penilaian awal medis ranap dewasa", Table: "penilaian_medis_ranap"},
	{Slug: "penilaian-medis-ranap-jantung", Label: "penilaian awal medis ranap jantung", Table: "penilaian_medis_ranap_jantung"},
	{Slug: "penilaian-medis-ranap-kandungan", Label: "penilaian awal medis ranap kandungan", Table: "penilaian_medis_ranap_kandungan"},
	{Slug: "penilaian-medis-ranap-neonatus", Label: "penilaian awal medis ranap neonatus", Table: "penilaian_medis_ranap_neonatus"},
	{Slug: "penilaian-medis-ranap-psikiatrik", Label: "penilaian awal medis ranap psikiatrik", Table: "penilaian_medis_ranap_psikiatrik"},
	{Slug: "penilaian-bayi-baru-lahir", Label: "penilaian bayi baru lahir", Table: "penilaian_bayi_baru_lahir"},
	{Slug: "penilaian-dehidrasi", Label: "penilaian derajat dehidrasi", Table: "penilaian_dehidrasi"},
	{Slug: "penilaian-fisioterapi", Label: "penilaian fisioterapi", Table: "penilaian_fisioterapi"},
	{Slug: "penilaian-korban-kekerasan", Label: "penilaian korban kekerasan", Table: "penilaian_korban_kekerasan"},
	{Slug: "penilaian-lanjutan-resiko-jatuh-anak", Label: "penilaian lanjutan risiko jatuh anak", Table: "penilaian_lanjutan_resiko_jatuh_anak"},
	{Slug: "penilaian-lanjutan-resiko-jatuh-dewasa", Label: "penilaian lanjutan risiko jatuh dewasa", Table: "penilaian_lanjutan_resiko_jatuh_dewasa"},
	{Slug: "penilaian-lanjutan-resiko-jatuh-geriatri", Label: "penilaian lanjutan risiko jatuh geriatri", Table: "penilaian_lanjutan_resiko_jatuh_geriatri"},
	{Slug: "penilaian-lanjutan-resiko-jatuh-lansia", Label: "penilaian lanjutan risiko jatuh lansia", Table: "penilaian_lanjutan_resiko_jatuh_lansia"},
	{Slug: "penilaian-lanjutan-resiko-jatuh-psikiatri", Label: "penilaian lanjutan risiko jatuh psikiatri", Table: "penilaian_lanjutan_resiko_jatuh_psikiatri"},
	{Slug: "penilaian-lanjutan-skrining-fungsional", Label: "penilaian lanjutan skrining fungsional", Table: "penilaian_lanjutan_skrining_fungsional"},
	{Slug: "penilaian-level-kecemasan-ranap-anak", Label: "penilaian level kecemasan ranap anak", Table: "penilaian_level_kecemasan_ranap_anak"},
	{Slug: "penilaian-pasien-imunitas-rendah", Label: "penilaian pasien imunitas rendah", Table: "penilaian_pasien_imunitas_rendah"},
	{Slug: "penilaian-pasien-keracunan", Label: "penilaian pasien keracunan", Table: "penilaian_pasien_keracunan"},
	{Slug: "penilaian-pasien-penyakit-menular", Label: "penilaian pasien penyakit menular", Table: "penilaian_pasien_penyakit_menular"},
	{Slug: "penilaian-pasien-terminal", Label: "penilaian pasien terminal", Table: "penilaian_pasien_terminal"},
	{Slug: "penilaian-pre-anestesi", Label: "penilaian pre anastesi", Table: "penilaian_pre_anestesi"},
	{Slug: "penilaian-pre-induksi", Label: "penilaian pre induksi", Table: "penilaian_pre_induksi"},
	{Slug: "penilaian-pre-operasi", Label: "penilaian pre operasi", Table: "penilaian_pre_operasi"},
	{Slug: "penilaian-psikologi", Label: "penilaian psikologi", Table: "penilaian_psikologi"},
	{Slug: "penilaian-psikologi-klinis", Label: "penilaian psikologi klinis", Table: "penilaian_psikologi_klinis"},
	{Slug: "penilaian-risiko-dekubitus", Label: "penilaian risiko dekubitus", Table: "penilaian_risiko_dekubitus"},
	{Slug: "penilaian-risiko-jatuh-neonatus", Label: "penilaian risiko jatuh neonatus", Table: "penilaian_risiko_jatuh_neonatus"},
	{Slug: "penilaian-tambahan-bunuh-diri", Label: "penilaian tambahan bunuh diri", Table: "penilaian_tambahan_bunuh_diri"},
	{Slug: "penilaian-tambahan-geriatri", Label: "penilaian tambahan geriatri", Table: "penilaian_tambahan_geriatri"},
	{Slug: "penilaian-tambahan-beresiko-melarikan-diri", Label: "penilaian tambahan melarikan diri", Table: "penilaian_tambahan_beresiko_melarikan_diri"},
	{Slug: "penilaian-tambahan-perilaku-kekerasan", Label: "penilaian tambahan perilaku kekerasan", Table: "penilaian_tambahan_perilaku_kekerasan"},
	{Slug: "penilaian-terapi-wicara", Label: "penilaian terapi wicara", Table: "penilaian_terapi_wicara"},
	{Slug: "penilaian-ulang-nyeri", Label: "penilaian ulang nyeri", Table: "penilaian_ulang_nyeri"},
	{Slug: "perencanaan-pemulangan", Label: "perencanaan pemulangan", Table: "perencanaan_pemulangan"},
	{Slug: "signin-sebelum-anestesi", Label: "sign in sebelum anastesi", Table: "signin_sebelum_anestesi"},
	{Slug: "signout-sebelum-menutup-luka", Label: "sign out sebelum menutup luka", Table: "signout_sebelum_menutup_luka"},
	{Slug: "skrining-adiksi-nikotin", Label: "skrining adiksi nikotin", Table: "skrining_adiksi_nikotin"},
	{Slug: "skrining-anemia", Label: "skrining anemia", Table: "skrining_anemia"},
	{Slug: "skrining-curb65", Label: "skrining 65", Table: "skrining_curb65"},
	{Slug: "skrining-diabetes-melitus", Label: "skrining diabetes melitus", Table: "skrining_diabetes_melitus"},
	{Slug: "skrining-frailty-syndrome", Label: "skrining frailty syndrome", Table: "skrining_frailty_syndrome"},
	{Slug: "skrining-hipertensi", Label: "skrining hipertensi", Table: "skrining_hipertensi"},
	{Slug: "skrining-indra-pendengaran", Label: "skrining indra pendengaran", Table: "skrining_indra_pendengaran"},
	{Slug: "skrining-instrumen-acrs", Label: "skrining instrumen ACRS", Table: "skrining_instrumen_acrs"},
	{Slug: "skrining-instrumen-amt", Label: "skrining instrumen AMT", Table: "skrining_instrumen_amt"},
	{Slug: "skrining-instrumen-esat", Label: "skrining instrumen ESAT", Table: "skrining_instrumen_esat"},
	{Slug: "skrining-instrumen-sdq", Label: "skrining instrumen SDQ", Table: "skrining_instrumen_sdq"},
	{Slug: "skrining-kanker-kolorektal", Label: "skrining kanker kolorektal", Table: "skrining_kanker_kolorektal"},
	{Slug: "skrining-kekerasan-pada-perempuan", Label: "skrining kekerasan pada perempuan", Table: "skrining_kekerasan_pada_perempuan"},
	{Slug: "skrining-kesehatan-gigi-mulut-balita", Label: "skrining kesehatan gigi mulut balita", Table: "skrining_kesehatan_gigi_mulut_balita"},
	{Slug: "skrining-kesehatan-gigi-mulut-dewasa", Label: "skrining kesehatan gigi mulut dewasa", Table: "skrining_kesehatan_gigi_mulut_dewasa"},
	{Slug: "skrining-kesehatan-gigi-mulut-lansia", Label: "skrining kesehatan gigi mulut lansia", Table: "skrining_kesehatan_gigi_mulut_lansia"},
	{Slug: "skrining-kesehatan-gigi-mulut-remaja", Label: "skrining kesehatan gigi mulut remaja", Table: "skrining_kesehatan_gigi_mulut_remaja"},
	{Slug: "skrining-kesehatan-penglihatan", Label: "skrining kesehatan penglihatan", Table: "skrining_kesehatan_penglihatan"},
	{Slug: "mpp-skrining", Label: "skrining MPP", Table: "mpp_skrining"},
	{Slug: "mpp-evaluasi", Label: "skrining MPP form a", Table: "mpp_evaluasi"},
	{Slug: "mpp-evaluasi-catatan", Label: "skrining MPP form b", Table: "mpp_evaluasi_catatan"},
	{Slug: "skrining-perilaku-merokok-sekolah-remaja", Label: "skrining merokok usia sekolah remaja", Table: "skrining_perilaku_merokok_sekolah_remaja"},
	{Slug: "skrining-nutrisi-anak", Label: "skrining nutrisi anak", Table: "skrining_nutrisi_anak"},
	{Slug: "skrining-nutrisi-dewasa", Label: "skrining nutrisi dewasa", Table: "skrining_nutrisi_dewasa"},
	{Slug: "skrining-nutrisi-lansia", Label: "skrining nutrisi lansia", Table: "skrining_nutrisi_lansia"},
	{Slug: "skrining-obesitas", Label: "skrining obesitas", Table: "skrining_obesitas"},
	{Slug: "skrining-puma", Label: "skrining PUMA", Table: "skrining_puma"},
	{Slug: "skrining-pneumonia-severity-index", Label: "skrining pneumonia severity index", Table: "skrining_pneumonia_severity_index"},
	{Slug: "skrining-risiko-kanker-paru", Label: "skrining risiko kanker paru", Table: "skrining_risiko_kanker_paru"},
	{Slug: "skrining-risiko-kanker-payudara", Label: "skrining risiko kanker payudara", Table: "skrining_risiko_kanker_payudara"},
	{Slug: "skrining-risiko-kanker-serviks", Label: "skrining risiko kanker serviks", Table: "skrining_risiko_kanker_serviks"},
	{Slug: "skrining-instrumen-srq", Label: "skrining SRQ", Table: "skrining_instrumen_srq"},
	{Slug: "skrining-tbc", Label: "skrining TBC", Table: "skrining_tbc"},
	{Slug: "skrining-tolac", Label: "skrining TOLAC", Table: "skrining_tolac"},
	{Slug: "skrining-thalassemia", Label: "skrining talasemia", Table: "skrining_thalassemia"},
	{Slug: "timeout-sebelum-insisi", Label: "time out sebelum insisi", Table: "timeout_sebelum_insisi"},
	{Slug: "transfer-pasien-antar-ruang", Label: "transfer pasien antar ruang", Table: "transfer_pasien_antar_ruang"},
	{Slug: "uji-fungsi-kfr", Label: "uji fungsi KFR", Table: "uji_fungsi_kfr"},
}
